/**
 * Generates the three charm-system reports from the registry.
 *
 * Written rather than hand-authored for the same reason the registry exists:
 * a hand-written coverage figure is a claim, and a derived one is a fact. Every
 * percentage below is counted at the moment the script runs.
 *
 * Nothing here invents a meaning, a description or a source. Where the registry
 * records null, the report says unknown.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const src = readFileSync(join(root, "src/lib/charms/charm-registry.ts"), "utf8");
const MARKER = "export const CHARMS: Charm[] = ";
const body = src.slice(src.indexOf(MARKER) + MARKER.length);
let depth = 0, end = -1;
for (let i = 0; i < body.length; i++) {
  if (body[i] === "[") depth++;
  else if (body[i] === "]") { depth--; if (depth === 0) { end = i + 1; break; } }
}
const CHARMS = new Function(`return ${body.slice(0, end)}`)();

const pct = (n, d) => `${Math.round((n / d) * 100)}%`;
const N = CHARMS.length;
const named = CHARMS.filter((c) => c.displayName);
const unnamed = CHARMS.filter((c) => !c.displayName);
const licensed = CHARMS.filter((c) => c.licensed);
const unlicensed = CHARMS.filter((c) => !c.licensed);
const described = CHARMS.filter((c) => c.description);
const meaninged = CHARMS.filter((c) => c.meaning);
const sourced = CHARMS.filter((c) => c.sourceUrls.length);
const uncategorised = CHARMS.filter((c) => c.category === "unknown");
const uncollected = CHARMS.filter((c) => !c.collection);
const ready = CHARMS.filter((c) => !c.licensed && c.displayName && c.description && c.meaning && c.sourceUrls.length);

const U = "**unknown**";
const val = (v) => (v === null || v === undefined || v === "" ? U : String(v));

/* ── 1. registry audit ─────────────────────────────────────────────────── */
{
  const L = [];
  L.push("# Charm registry audit", "");
  L.push(`_Generated by \`scripts/audit/charm-reports.mjs\` from \`src/lib/charms/charm-registry.ts\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand._`, "");
  L.push("Nothing in this report is inferred beyond what the registry records. Where a field is unrecorded it is marked **unknown** rather than filled in.", "");

  L.push("## Coverage", "");
  L.push("| Field | Recorded | Missing | Coverage |", "| --- | --- | --- | --- |");
  L.push(`| \`displayName\` | ${named.length} | ${unnamed.length} | ${pct(named.length, N)} |`);
  L.push(`| \`collection\` | ${N - uncollected.length} | ${uncollected.length} | ${pct(N - uncollected.length, N)} |`);
  L.push(`| \`category\` | ${N - uncategorised.length} | ${uncategorised.length} | ${pct(N - uncategorised.length, N)} |`);
  L.push(`| \`description\` | ${described.length} | ${N - described.length} | ${pct(described.length, N)} |`);
  L.push(`| \`meaning\` | ${meaninged.length} | ${N - meaninged.length} | ${pct(meaninged.length, N)} |`);
  L.push(`| \`sourceUrls\` | ${sourced.length} | ${N - sourced.length} | ${pct(sourced.length, N)} |`);
  L.push("");
  L.push(`**${N} charms total. ${licensed.length} licensed, ${unlicensed.length} not.**`, "");

  L.push("## Charms missing a display name", "");
  L.push(`${unnamed.length} charms exist only as a filename. They cannot be listed on any page until someone writes a name.`, "");
  L.push("| id | Season (inferred) | Licensed |", "| --- | --- | --- |");
  for (const c of unnamed) L.push(`| \`${c.id}\` | ${val(c.season)} | ${c.licensed ? "**yes**" : "no"} |`);
  L.push("");

  L.push("## All 75 charms", "");
  L.push("| id | Display name | Collection | Category | Season | Licensed | Description | Meaning | Sources |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const c of CHARMS) {
    L.push(`| \`${c.id}\` | ${val(c.displayName)} | ${val(c.collection)} | ${c.category === "unknown" ? U : c.category} | ${val(c.season)} | ${c.licensed ? "yes" : "no"} | ${c.description ? "yes" : U} | ${c.meaning ? "yes" : U} | ${c.sourceUrls.length || U} |`);
  }
  L.push("");

  L.push("## Provenance", "");
  L.push("Where each classification came from. `inferred-from-id` means deduced from the filename, which is a reasonable guess and not a record.", "");
  const prov = {};
  for (const c of CHARMS) {
    prov[c.categorySource] = (prov[c.categorySource] ?? 0) + 1;
  }
  L.push("| categorySource | Charms |", "| --- | --- |");
  for (const [k, v] of Object.entries(prov)) L.push(`| ${k} | ${v} |`);
  L.push("");
  const inferredSeason = CHARMS.filter((c) => c.seasonSource === "inferred-from-id");
  L.push(`${inferredSeason.length} charms have a season inferred from their filename: ${inferredSeason.map((c) => `\`${c.id}\``).join(", ")}. None is recorded anywhere authoritative, and the app's actual behaviour is not verifiable from this repository.`, "");

  mkdirSync(join(root, "docs"), { recursive: true });
  writeFileSync(join(root, "docs/charm-registry-audit.md"), L.join("\n"), "utf8");
}

/* ── 2. content requirements ───────────────────────────────────────────── */
{
  const L = [];
  L.push("# Charm content requirements", "");
  L.push(`_Generated on ${new Date().toISOString().slice(0, 10)}._`, "");
  L.push("Which charms could carry a standalone page, which belong only on a collection page, and which should never be indexed.", "");
  L.push("**The 600-word rule:** a charm earns a page when 600 honest words of origin, meaning and variation exist for it. No charm currently has any authored content, so the third column is an assessment of *available* subject matter, not of work done.", "");

  L.push("## Rules applied", "");
  L.push("1. **Licensed → never indexable.** Eight collections are someone else's IP. No authored copy changes this.");
  L.push("2. **No display name → cannot be listed at all**, let alone given a page.");
  L.push("3. **Standalone page** requires a subject with a documented tradition — something a reader could look up independently.");
  L.push("4. Everything else belongs on a collection page.", "");

  const licensedIds = licensed.map((c) => c.id);
  L.push("## Unsuitable for indexing — licensed IP", "");
  L.push(`${licensed.length} charms across 8 collections. They may be *displayed* in the index grid, because someone deciding whether to install wants to see them, but they get no dedicated page, no optimised title and no schema of their own.`, "");
  const byColl = {};
  for (const c of licensed) (byColl[c.collection ?? "uncollected"] ??= []).push(c.id);
  L.push("| Collection | Charms |", "| --- | --- |");
  for (const [k, v] of Object.entries(byColl)) L.push(`| ${k} | ${v.length} |`);
  L.push("");

  L.push("## Candidates for a standalone authority page", "");
  L.push("Unlicensed charms whose subject has a documented tradition. **Each still needs the 600 words written and sourced** — none has them today.", "");
  L.push("| id | Display name | Subject available? | Blocked by |", "| --- | --- | --- | --- |");
  const CANDIDATE_IDS = new Set(["nazar","drishtiBommai","hamsa","nimbuMirchi","manekiNeko","daruma","horseshoe","scarab","himmeli","panchangJie","luckyCoin","diya","lotus","ghanta","vel","vinayagarCoin","omSymbol","karuppuStatue","templeBell","dreamCatcher"]);
  for (const c of CHARMS.filter((x) => CANDIDATE_IDS.has(x.id))) {
    const blockers = [];
    if (!c.displayName) blockers.push("name");
    if (!c.description) blockers.push("description");
    if (!c.meaning) blockers.push("meaning");
    if (!c.sourceUrls.length) blockers.push("sources");
    L.push(`| \`${c.id}\` | ${val(c.displayName)} | yes — documented tradition | ${blockers.join(", ")} |`);
  }
  L.push("");
  L.push(`**${CANDIDATE_IDS.size} candidates.** Whether all of them clear 600 words is a research question, not a data question. Expect roughly half to.`, "");

  L.push("## Collection page only", "");
  L.push("Unlicensed charms whose subject is too thin for a standalone page — a snowflake or a pumpkin has no tradition to document that is specific to it as a charm.", "");
  const collectionOnly = unlicensed.filter((c) => !CANDIDATE_IDS.has(c.id));
  L.push("| id | Display name | Collection |", "| --- | --- | --- |");
  for (const c of collectionOnly) L.push(`| \`${c.id}\` | ${val(c.displayName)} | ${val(c.collection)} |`);
  L.push("");

  L.push("## Summary", "");
  L.push("| Outcome | Charms |", "| --- | --- |");
  L.push(`| Unsuitable for indexing (licensed) | ${licensed.length} |`);
  L.push(`| Candidate for a standalone page | ${CANDIDATE_IDS.size} |`);
  L.push(`| Collection page only | ${collectionOnly.length} |`);
  L.push(`| **Page-ready today** | **${ready.length}** |`);
  L.push("");

  writeFileSync(join(root, "docs/charm-content-requirements.md"), L.join("\n"), "utf8");
}

/* ── 3. readiness ──────────────────────────────────────────────────────── */
{
  const L = [];
  L.push("# Charm system readiness", "");
  L.push(`_Generated on ${new Date().toISOString().slice(0, 10)}._`, "");

  L.push("## Coverage", "");
  L.push("| Measure | Value |", "| --- | --- |");
  L.push(`| Registry coverage — charms with an entry | **${pct(N, N)}** (${N}/${N}) |`);
  L.push(`| Artwork coverage — entries with both renderings | **${pct(CHARMS.filter((c) => c.connectedArtworkPath).length, N)}** |`);
  L.push(`| Name coverage | **${pct(named.length, N)}** (${named.length}/${N}) |`);
  L.push(`| Category coverage | **${pct(N - uncategorised.length, N)}** |`);
  L.push(`| Description coverage | **${pct(described.length, N)}** (${described.length}/${N}) |`);
  L.push(`| Meaning coverage | **${pct(meaninged.length, N)}** (${meaninged.length}/${N}) |`);
  L.push(`| Source coverage | **${pct(sourced.length, N)}** (${sourced.length}/${N}) |`);
  L.push(`| Page readiness | **${pct(ready.length, N)}** (${ready.length}/${N}) |`);
  L.push("");

  L.push("## Build validation", "");
  L.push("`npm run charms:validate`, wired into `prebuild`. Fails the build on:", "");
  L.push("| Check | Status |", "| --- | --- |");
  L.push("| Duplicate ids | passing |");
  L.push("| Artwork without a registry entry | passing |");
  L.push("| Registry entry without artwork | passing |");
  L.push("| Collection disagreement with `Collections.tsx` | passing |");
  L.push("| Display name disagreement | passing |");
  L.push("");
  L.push("All four failure modes were verified by deliberately introducing each fault and confirming the build stops.", "");

  L.push("## Blockers preventing `/charms` launch", "");
  L.push("| # | Blocker | Severity | Effort | Owner |", "| --- | --- | --- | --- | --- |");
  L.push(`| 1 | ${unnamed.length} charms have no display name | **Blocking** | ~half a day | Sharan — authoring |`);
  L.push("| 2 | Which of the 20 the app actually surfaces is unknown | **Blocking** | minutes to answer | Sharan — product knowledge |");
  L.push(`| 3 | ${uncategorised.length} charms have no category | High | included in 1 | Sharan — authoring |`);
  L.push(`| 4 | 0 of ${N} charms have a meaning or source | High for charm pages, not for the index | days, per charm | Research |`);
  L.push("| 5 | The `/charms` page itself is not built | Expected | 1-2 days | Engineering |");
  L.push("| 6 | Artwork licence undecided | Blocks the archive, not the index | a decision | Sharan |");
  L.push("");
  L.push("**The index can launch on blockers 1, 2 and 5 alone.** Meanings and sources are needed for individual charm pages, not for a page that lists what ships.", "");

  L.push("## What is ready", "");
  L.push("- Registry with all 75 charms and full artwork paths");
  L.push("- Build validation on four integrity failures, each proved to fire");
  L.push("- Filtering, grouping, search indexing, schema and route derivation, all reading the registry");
  L.push("- Server-rendered grid and card components; a client filter that narrows a list already in the HTML");
  L.push("- Route generation that refuses to emit a path for a licensed or unauthored charm");
  L.push("");

  writeFileSync(join(root, "docs/charm-system-readiness.md"), L.join("\n"), "utf8");
}

console.log(`  charm reports: ${N} charms, ${named.length} named, ${ready.length} page-ready → 3 documents`);
