/**
 * Measures conversion surface across every exported page.
 *
 * An opinion about CTAs is worth little; this counts them. For each page it
 * records whether a download route is reachable, how far down the document the
 * first one appears, how many there are, and whether the page can be reached
 * from the home page at all. Judgement still goes into the recommendations at
 * the end, but it is judgement applied to measurements.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const out = join(root, "out");

function walk(dir, found = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) { if (e !== "_next") walk(p, found); }
    else if (e.endsWith(".html")) found.push(p);
  }
  return found;
}

const EXCLUDE = new Set(["/404", "/_not-found", "/products/vision/release-notes", "/products/vision/dev/release-notes"]);
const pages = new Map();
for (const f of walk(out)) {
  const path = `/${relative(out, f).replace(/\.html$/, "")}`.replace(/^\/index$/, "/");
  if (!EXCLUDE.has(path)) pages.set(path, readFileSync(f, "utf8"));
}

/** Anything that starts a download or leads directly to one. */
const DOWNLOAD_HREF = /href="(\/download(?:\/[a-z]+)?|\/products\/(?:hangly|vision)\/download[^"]*|\/install)"/g;

const rows = [];
for (const [path, html] of pages) {
  const bodyStart = html.indexOf("<body");
  const body = html.slice(bodyStart < 0 ? 0 : bodyStart);
  const hits = [...body.matchAll(DOWNLOAD_HREF)];
  const first = hits.length ? hits[0].index / body.length : null;
  // The download button renders as a <button> before platform detection runs,
  // so a page can carry a working CTA with no matching href in the HTML.
  const hasButton = /class="button button-primary"/.test(body) || /hangly:choose-platform|aria-haspopup="dialog"/.test(body);
  const internal = new Set([...body.matchAll(/href="(\/[^"#?]*)"/g)].map((m) => m[1].replace(/\/$/, "") || "/")).size;
  rows.push({
    path,
    downloadLinks: hits.length,
    firstAt: first === null ? null : Math.round(first * 100),
    hasButton,
    internal,
    words: body.replace(/<script[\s\S]*?<\/script>/g, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().split(" ").length,
  });
}
rows.sort((a, b) => a.path.localeCompare(b.path));

const noCta = rows.filter((r) => !r.downloadLinks && !r.hasButton);
const deepCta = rows.filter((r) => r.downloadLinks && r.firstAt !== null && r.firstAt > 60);

const L = [];
L.push("# Conversion audit", "");
L.push(`_Generated by \`scripts/audit/conversion.mjs\` from \`out/\` on ${new Date().toISOString().slice(0, 10)}. Measurements are counted; recommendations are judgement applied to them._`, "");
L.push("Nothing in this report has been implemented. It is a list of findings.", "");

L.push("## Summary", "");
L.push("| Measure | Value |", "| --- | --- |");
L.push(`| Pages audited | ${rows.length} |`);
L.push(`| Pages with no download CTA at all | ${noCta.length} |`);
L.push(`| Pages where the first CTA is below 60% depth | ${deepCta.length} |`);
L.push(`| Median download links per page | ${[...rows].map((r) => r.downloadLinks).sort((a, b) => a - b)[Math.floor(rows.length / 2)]} |`);
L.push("");

L.push("## Per page", "");
L.push("`First CTA` is how far down the document the first download link appears, as a percentage of total markup. `Button` means a platform-detecting download button is present, which renders as a `<button>` before detection resolves and so carries no href.", "");
L.push("| Page | Download links | First CTA | Button | Internal links | Words |", "| --- | --- | --- | --- | --- | --- |");
for (const r of rows) {
  L.push(`| \`${r.path}\` | ${r.downloadLinks} | ${r.firstAt === null ? "—" : r.firstAt + "%"} | ${r.hasButton ? "yes" : "—"} | ${r.internal} | ${r.words} |`);
}
L.push("");

L.push("## Findings", "");

L.push("### 1. Pages with no route to a download", "");
if (noCta.length) {
  L.push("These pages cannot convert. A reader who arrives here has to navigate before they can act.", "");
  for (const r of noCta) L.push(`- \`${r.path}\` — ${r.words} words, ${r.internal} internal links`);
} else {
  L.push("None. Every audited page carries either a download link or a platform-detecting download button.");
}
L.push("");

L.push("### 2. Pages where the first CTA is buried", "");
if (deepCta.length) {
  L.push("The first download link sits past 60% of the document. On these pages a reader who does not scroll to the end never sees one.", "");
  for (const r of deepCta) L.push(`- \`${r.path}\` — first CTA at ${r.firstAt}% depth`);
} else {
  L.push("None.");
}
L.push("");

mkdirSync(join(root, "docs"), { recursive: true });
// Measurements only. The findings in docs/conversion-audit.md are judgement
// applied to these and are maintained by hand, so this never overwrites them.
writeFileSync(join(root, "docs/conversion-measurements.md"), L.join("\n"), "utf8");
console.log(`  conversion: ${rows.length} pages, ${noCta.length} with no CTA, ${deepCta.length} with a buried CTA`);
