/**
 * Reports the entity graph as it actually ships, into docs/entity-graph-report.md.
 *
 * Written rather than hand-authored because a hand-authored graph report is a
 * description of what someone intended. This reads out/, so it describes what
 * a crawler will find.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const out = join(root, "out");
const SITE = "https://www.sharancreatedthis.in";

function walk(dir, found = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) { if (e !== "_next") walk(p, found); }
    else if (e.endsWith(".html")) found.push(p);
  }
  return found;
}

const pages = new Map();
for (const f of walk(out)) {
  const path = `/${relative(out, f).replace(/\.html$/, "")}`.replace(/^\/index$/, "/");
  pages.set(path, readFileSync(f, "utf8"));
}

/** Every node keyed by @id, plus which pages declare it and what it points at. */
const declared = new Map();
const edges = new Map();
let referenceCount = 0, danglingCount = 0;
const dangling = [];

const EDGE_KEYS = new Set([
  "founder", "author", "creator", "publisher", "provider", "brand", "owns",
  "worksFor", "about", "isPartOf", "mainEntity", "copyrightHolder", "seller",
]);

for (const [path, html] of pages) {
  const pageDeclared = new Set();
  const pageRefs = [];
  for (const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    let parsed;
    try { parsed = JSON.parse(m[1]); } catch { continue; }
    (function visit(node, key) {
      if (Array.isArray(node)) return node.forEach((n) => visit(n, key));
      if (!node || typeof node !== "object") return;
      if (node["@id"] && node["@type"]) {
        pageDeclared.add(node["@id"]);
        const rec = declared.get(node["@id"]) ?? { type: node["@type"], pages: new Set(), props: new Set() };
        rec.type = node["@type"];
        rec.pages.add(path);
        for (const k of Object.keys(node)) if (!k.startsWith("@")) rec.props.add(k);
        declared.set(node["@id"], rec);
        for (const [k, v] of Object.entries(node)) {
          if (!EDGE_KEYS.has(k)) continue;
          for (const target of (Array.isArray(v) ? v : [v])) {
            if (target && typeof target === "object" && target["@id"]) {
              const set = edges.get(node["@id"]) ?? new Set();
              set.add(`${k} → ${target["@id"]}`);
              edges.set(node["@id"], set);
            }
          }
        }
      } else if (node["@id"] && !node["@type"]) {
        pageRefs.push(node["@id"]);
      }
      for (const [k, v] of Object.entries(node)) visit(v, k);
    })(parsed);
  }
  for (const ref of pageRefs) {
    referenceCount++;
    if (!pageDeclared.has(ref)) { danglingCount++; dangling.push(`${path} → ${ref}`); }
  }
}

const CORE = [`${SITE}/#person-sharan`, `${SITE}/#organization`, `${SITE}/#website`,
              `${SITE}/products/hangly#hangly`, `${SITE}/products/vision#vision`];

const lines = [];
lines.push("# Entity graph report", "");
lines.push(`_Generated by \`scripts/audit/entity-graph.mjs\` from \`out/\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand._`, "");
lines.push("This describes the graph a crawler will actually find, not the one intended.", "");

lines.push("## Summary", "");
lines.push("| Measure | Value |", "| --- | --- |");
lines.push(`| Pages analysed | ${pages.size} |`);
lines.push(`| Distinct \`@id\` nodes declared | ${declared.size} |`);
lines.push(`| \`@id\` references | ${referenceCount} |`);
lines.push(`| Dangling references | ${danglingCount} |`);
lines.push("");

lines.push("## The five core entities", "");
lines.push("These must appear on every page for the graph to resolve from anywhere.", "");
lines.push("| Entity | Type | Pages | Properties |", "| --- | --- | --- | --- |");
for (const id of CORE) {
  const rec = declared.get(id);
  lines.push(rec
    ? `| \`${id.replace(SITE, "")}\` | ${rec.type} | ${rec.pages.size}/${pages.size} | ${rec.props.size} |`
    : `| \`${id.replace(SITE, "")}\` | **MISSING** | 0 | 0 |`);
}
lines.push("");

lines.push("## Edges between the core entities", "");
lines.push("The relationships that tell an answer engine who made what.", "");
lines.push("```");
for (const id of CORE) {
  const set = edges.get(id);
  if (!set) continue;
  lines.push(id.replace(SITE, "") || "/");
  for (const e of [...set].sort()) lines.push("    " + e.replace(new RegExp(SITE, "g"), ""));
}
lines.push("```", "");

lines.push("## Properties carried by each core entity", "");
for (const id of CORE) {
  const rec = declared.get(id);
  if (!rec) continue;
  lines.push(`**\`${id.replace(SITE, "")}\`** (${rec.type})`, "");
  lines.push("`" + [...rec.props].sort().join("`, `") + "`", "");
}

lines.push("## Dangling references", "");
lines.push(danglingCount
  ? ["These are `@id` pointers to nodes nothing on the page declares. Each is invisible in a browser and silently breaks the graph.", "", ...dangling.map((d) => `- ${d.replace(new RegExp(SITE, "g"), "")}`)].join("\n")
  : "None. Every `@id` referenced on every page is declared on that same page.");
lines.push("");

lines.push("## All declared nodes", "");
lines.push("| `@id` | Type | Pages |", "| --- | --- | --- |");
for (const [id, rec] of [...declared].sort((a, b) => a[0].localeCompare(b[0]))) {
  lines.push(`| \`${id.replace(SITE, "") || "/"}\` | ${rec.type} | ${rec.pages.size} |`);
}
lines.push("");

mkdirSync(join(root, "docs"), { recursive: true });
writeFileSync(join(root, "docs/entity-graph-report.md"), lines.join("\n"), "utf8");
console.log(`  entity-graph: ${declared.size} nodes, ${referenceCount} references, ${danglingCount} dangling → docs/entity-graph-report.md`);
