/**
 * Word counts per page, before and after the expansion pass.
 *
 * "Thin" is not a fixed number, but under 250 words of visible text is where
 * Google's own guidance and this project's validator agree something is
 * likely too slight to rank. The baseline below is recorded from the state at
 * the start of this phase so the delta is checkable rather than claimed.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const out = join(root, "out");

/** Measured from the export at commit 066e7d8, before this phase. */
const BASELINE = { "/contact": 93, "/portfolio": 230, "/products": 161 };
const TARGET = { "/contact": "500-800", "/products": "800-1200", "/portfolio": "1000-1500" };

function walk(dir, found = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) { if (e !== "_next") walk(p, found); }
    else if (e.endsWith(".html")) found.push(p);
  }
  return found;
}
const EXCLUDE = new Set(["/404", "/_not-found", "/products/vision/release-notes", "/products/vision/dev/release-notes"]);
const rows = [];
for (const f of walk(out)) {
  const path = `/${relative(out, f).replace(/\.html$/, "")}`.replace(/^\/index$/, "/");
  if (EXCLUDE.has(path)) continue;
  const h = readFileSync(f, "utf8");
  const words = h.replace(/<script[\s\S]*?<\/script>/g, " ").replace(/<style[\s\S]*?<\/style>/g, " ")
    .replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().split(" ").length;
  const schema = new Set();
  for (const m of h.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    try { (function v(n) { if (Array.isArray(n)) return n.forEach(v); if (!n || typeof n !== "object") return;
      if (n["@type"]) schema.add(n["@type"]); Object.values(n).forEach(v); })(JSON.parse(m[1])); } catch {}
  }
  rows.push({ path, words, schema: [...schema].sort() });
}
rows.sort((a, b) => a.words - b.words);

const thin = rows.filter((r) => r.words < 250);
const L = [];
L.push("# Thin page report", "");
L.push(`_Generated by \`scripts/audit/thin-pages.mjs\` from \`out/\` on ${new Date().toISOString().slice(0, 10)}._`, "");

L.push("## The three pages this phase targeted", "");
L.push("| Page | Before | After | Target | Met | Schema |", "| --- | --- | --- | --- | --- | --- |");
for (const p of Object.keys(BASELINE)) {
  const r = rows.find((x) => x.path === p);
  const [lo, hi] = TARGET[p].split("-").map(Number);
  const met = r.words >= lo ? (r.words <= hi ? "yes" : "exceeded") : "no";
  L.push(`| \`${p}\` | ${BASELINE[p]} | **${r.words}** | ${TARGET[p]} | ${met} | ${r.schema.join(", ")} |`);
}
L.push("");
L.push("Word counts include shared navigation and footer chrome, which is roughly 120 words per page on the hub layout. The prose added is the difference net of that.", "");

L.push("## Pages still under 250 words", "");
if (!thin.length) L.push("None. Every exported page renders at least 250 words of visible text server-side.");
else { L.push("| Page | Words |", "| --- | --- |"); for (const r of thin) L.push(`| \`${r.path}\` | ${r.words} |`); }
L.push("");

L.push("## Every page by length", "");
L.push("| Page | Words |", "| --- | --- |");
for (const r of rows) L.push(`| \`${r.path}\` | ${r.words} |`);
L.push("");

mkdirSync(join(root, "docs"), { recursive: true });
writeFileSync(join(root, "docs/thin-page-report.md"), L.join("\n"), "utf8");
console.log(`  thin-pages: ${rows.length} pages, ${thin.length} under 250 words`);
