/**
 * Renders docs/content-verification-report.md from the claims register.
 *
 * The register is TypeScript so the build type-checks it; this script strips
 * it to JSON rather than importing, which keeps the audit runnable without a
 * TypeScript toolchain in the loop.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const src = readFileSync(join(root, "src/lib/verification/claims.ts"), "utf8");

// The register uses named date constants so a re-verification pass updates one
// line rather than thirty. Carry them into the eval scope rather than inlining
// them in the source, which would defeat the point.
const dates = [...src.matchAll(/^const ([A-Z_]+) = ("[\d-]+");$/gm)]
  .map((m) => `const ${m[1]} = ${m[2]};`)
  .join("\n");
const body = src.slice(src.indexOf("export const CLAIMS: Claim[] = ["));
const json = body.slice(body.indexOf("["), body.lastIndexOf("];") + 1);
const claims = new Function(`${dates}\nreturn ${json.replace(/,(\s*[}\]])/g, "$1")}`)();

const CONF_ORDER = { none: 0, low: 1, medium: 2, high: 3 };
const counts = claims.reduce((acc, c) => ((acc[c.confidence] = (acc[c.confidence] ?? 0) + 1), acc), {});
const unverified = claims.filter((c) => !c.verified);

const L = [];
L.push("# Content verification report", "");
L.push(`_Generated by \`scripts/audit/verification.mjs\` from \`src/lib/verification/claims.ts\` on ${new Date().toISOString().slice(0, 10)}._`, "");
L.push("Every factual claim the site makes about itself or a competitor, with its source, whether it was verified, when it was last read, and an honest confidence.", "");
L.push("No content was changed to produce this report. It is a description of the current state.", "");

L.push("## Summary", "");
L.push("| Measure | Count |", "| --- | --- |");
L.push(`| Claims audited | ${claims.length} |`);
L.push(`| Verified | ${claims.filter((c) => c.verified).length} |`);
L.push(`| **Unverified** | **${unverified.length}** |`);
L.push(`| High confidence | ${counts.high ?? 0} |`);
L.push(`| Medium confidence | ${counts.medium ?? 0} |`);
L.push(`| Low confidence | ${counts.low ?? 0} |`);
L.push(`| No confidence | ${counts.none ?? 0} |`);
L.push("");

const flagged = claims.filter((c) => c.confidence === "none");
L.push("## Flagged — act on these", "");
if (!flagged.length) L.push("None.");
for (const c of flagged) {
  L.push(`### ${c.claim}`, "");
  L.push(`- **Appears on:** ${c.surface}`);
  L.push(`- **Source:** ${c.source || "_none_"}`);
  L.push(`- **Verified:** no`);
  L.push(`- **Last checked:** ${c.lastChecked}`);
  L.push(`- **Confidence:** none`);
  if (c.note) L.push("", c.note);
  L.push("");
}

L.push("## Unverified or low confidence", "");
L.push("| Claim | Where | Source | Confidence | Last checked |", "| --- | --- | --- | --- | --- |");
for (const c of claims.filter((x) => !x.verified || x.confidence === "low").sort((a, b) => CONF_ORDER[a.confidence] - CONF_ORDER[b.confidence])) {
  L.push(`| ${c.claim} | ${c.surface} | ${c.source ? `\`${c.source}\`` : "_none_"} | ${c.confidence} | ${c.lastChecked} |`);
}
L.push("");

L.push("## Full register", "");
L.push("| Claim | Where | Source | Verified | Last checked | Confidence |", "| --- | --- | --- | --- | --- | --- |");
for (const c of [...claims].sort((a, b) => CONF_ORDER[a.confidence] - CONF_ORDER[b.confidence])) {
  L.push(`| ${c.claim} | ${c.surface} | ${c.source ? `\`${c.source}\`` : "_none_"} | ${c.verified ? "yes" : "**no**"} | ${c.lastChecked} | ${c.confidence} |`);
}
L.push("");

L.push("## Notes on individual claims", "");
for (const c of claims.filter((x) => x.note && x.confidence !== "none")) {
  L.push(`**${c.claim}**`, "", c.note, "");
}

L.push("## How to re-verify", "");
L.push("1. Our own product figures are generated at build time by `scripts/generate-stats.mjs` and `scripts/generate-changelog.mjs`. They cannot drift; if one is wrong the source data is wrong.");
L.push("2. Competitor claims carry a check date on the page they appear on. Re-read the source URL and update both the claim and `lastChecked` in `src/lib/verification/claims.ts`.");
L.push("3. Star counts, prices and version numbers move. Anything older than about 90 days should be treated as low confidence regardless of what this table says.");
L.push("");

mkdirSync(join(root, "docs"), { recursive: true });
writeFileSync(join(root, "docs/content-verification-report.md"), L.join("\n"), "utf8");
console.log(`  verification: ${claims.length} claims, ${unverified.length} unverified, ${counts.none ?? 0} flagged → docs/content-verification-report.md`);
