/**
 * Counts what Hangly actually ships, from the files that define it.
 *
 * The statistics page exists to be cited, which means every number on it has
 * to be derivable rather than asserted. Hardcoding them is how a site ends up
 * claiming a charm count that nothing in the repository supports — which is
 * precisely what happened here: "80+" was written into twenty-odd places by
 * hand while the collections component listed 55.
 *
 * So the numbers come from source:
 *   collections + charms   src/components/hangly/Collections.tsx
 *   artwork files          public/charms/
 *   versions               the Sparkle feeds and public/_redirects
 *
 * If a number here looks wrong, the data is wrong, and that is the point.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

/* ── collections and charms, from the component that renders them ──────── */
const src = read("src/components/hangly/Collections.tsx");
const listStart = src.indexOf("export const collections");
const list = src.slice(listStart, src.indexOf("\n];", listStart));

const collections = [];
for (const block of list.split(/\n  \{\n/).slice(1)) {
  const name = (block.match(/name:\s*"([^"]+)"/) || [])[1];
  const description = (block.match(/description:\s*"([^"]+)"/) || [, ""])[1];
  // Each charm is a ["id", "Label"] pair.
  const charms = [...block.matchAll(/\[\s*"([A-Za-z0-9]+)"\s*,\s*"([^"]+)"\s*\]/g)].map((m) => m[2]);
  if (name) collections.push({ name, description, charms });
}

/* ── artwork actually on disk ──────────────────────────────────────────── */
const count = (dir) => (existsSync(join(root, dir)) ? readdirSync(join(root, dir)).filter((f) => f.endsWith(".svg")).length : 0);
const artwork = { plain: count("public/charms"), connected: count("public/charms/connected") };

/* ── versions, from the same feeds the updaters read ───────────────────── */
const feed = (p) => {
  const xml = read(p);
  const short = (xml.match(/sparkle:shortVersionString="([^"]+)"/) || xml.match(/<sparkle:shortVersionString>([^<]+)</) || [])[1];
  const min = (xml.match(/sparkle:minimumSystemVersion="([^"]+)"/) || xml.match(/<sparkle:minimumSystemVersion>([^<]+)</) || [])[1];
  const bytes = Number((xml.match(/length="(\d+)"/) || [, 0])[1]);
  const date = (xml.match(/<pubDate>([^<]+)</) || [])[1];
  return { version: short ?? "", minimumSystem: min ?? "", bytes, date: date ? new Date(date).toISOString().slice(0, 10) : "" };
};
const macOS = feed("public/products/hangly/appcast.xml");
const windows = (read("public/_redirects").match(/Hangly-Windows\/releases\/download\/v([\d.]+)\//) || [, ""])[1];

const charmTotal = collections.reduce((n, c) => n + c.charms.length, 0);

writeFileSync(
  join(root, "src/data/stats.generated.ts"),
  `// Generated by scripts/generate-stats.mjs. Do not edit — change the source data.\n` +
    `export type CharmCollection = { name: string; description: string; charms: string[] };\n\n` +
    `/** Collections and their charms, read from the component that renders them. */\n` +
    `export const COLLECTIONS: CharmCollection[] = ${JSON.stringify(collections, null, 2)};\n\n` +
    `/** Charms listed across every collection on the product page. */\n` +
    `export const CHARM_COUNT = ${charmTotal};\n\n` +
    `/** SVG files present in public/charms. Higher than CHARM_COUNT: it includes\n` +
    ` *  artwork for charms not currently listed in a collection. */\n` +
    `export const ARTWORK = ${JSON.stringify(artwork)};\n\n` +
    `export const RELEASE = ${JSON.stringify({ macOS, windows }, null, 2)};\n\n` +
    `export const GENERATED_AT = ${JSON.stringify(new Date().toISOString().slice(0, 10))};\n`,
  "utf8",
);
console.log(
  `  stats: ${collections.length} collections, ${charmTotal} charms listed, ` +
    `${artwork.plain} artwork files, macOS ${macOS.version}, Windows ${windows}`,
);
