/**
 * Counts what Hangly actually ships, from the files that define it.
 *
 * The statistics page exists to be cited, which means every number on it has
 * to be derivable rather than asserted. Hardcoding them is how a site ends up
 * claiming a charm count that nothing in the repository supports — which is
 * precisely what happened here: "80+" was written into twenty-odd places by
 * hand while the collections component listed 55.
 *
 * So the numbers come from source:
 *   collections + charms   src/components/hangly/Collections.tsx
 *   artwork files          public/charms/
 *   versions               the Sparkle feeds and public/_redirects
 *
 * If a number here looks wrong, the data is wrong, and that is the point.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

/* ── collections and charms, from the component that renders them ──────── */
const src = read("src/components/hangly/Collections.tsx");
const listStart = src.indexOf("export const collections");
const list = src.slice(listStart, src.indexOf("\n];", listStart));

const collections = [];
for (const block of list.split(/\n  \{\n/).slice(1)) {
  const name = (block.match(/name:\s*"([^"]+)"/) || [])[1];
  const description = (block.match(/description:\s*"([^"]+)"/) || [, ""])[1];
  // Each charm is a ["id", "Label"] pair.
  const charms = [...block.matchAll(/\[\s*"([A-Za-z0-9]+)"\s*,\s*"([^"]+)"\s*\]/g)].map((m) => m[2]);
  if (name) collections.push({ name, description, charms });
}

/* ── artwork actually on disk ──────────────────────────────────────────────
   This is the authoritative count. A charm exists for a user when its artwork
   ships, not when a marketing page mentions it: twenty of these are seasonal
   and lucky charms that arrive on their own and are named in no collection,
   which is exactly why counting the collections alone understated the library
   by a quarter. */
const svgs = (dir) => (existsSync(join(root, dir)) ? readdirSync(join(root, dir)).filter((f) => f.endsWith(".svg")).map((f) => f.replace(/\.svg$/, "")) : []);
const plain = svgs("public/charms");
const connected = svgs("public/charms/connected");
// A charm is complete only with both renderings: the plain drawing and the
// one with the hanging thread, which ends at that charm's own loop.
const complete = plain.filter((n) => connected.includes(n)).sort();
const artwork = { plain: plain.length, connected: connected.length, complete: complete.length };

const inCollections = new Set(collections.flatMap((c) => c.charms));

/* ── versions, from the same feeds the updaters read ───────────────────── */
const feed = (p) => {
  const xml = read(p);
  const short = (xml.match(/sparkle:shortVersionString="([^"]+)"/) || xml.match(/<sparkle:shortVersionString>([^<]+)</) || [])[1];
  const min = (xml.match(/sparkle:minimumSystemVersion="([^"]+)"/) || xml.match(/<sparkle:minimumSystemVersion>([^<]+)</) || [])[1];
  const bytes = Number((xml.match(/length="(\d+)"/) || [, 0])[1]);
  const date = (xml.match(/<pubDate>([^<]+)</) || [])[1];
  return { version: short ?? "", minimumSystem: min ?? "", bytes, date: date ? new Date(date).toISOString().slice(0, 10) : "" };
};
const macOS = feed("public/products/hangly/appcast.xml");
const windows = (read("public/_redirects").match(/Hangly-Windows\/releases\/download\/v([\d.]+)\//) || [, ""])[1];

const charmTotal = collections.reduce((n, c) => n + c.charms.length, 0);

/* Charms with artwork that no collection names. Seasonal and lucky charms
   that the app surfaces on its own — Halloween, Diwali, winter, and luck
   charms from several cultures. They are real and downloadable; they simply
   are not grouped on the product page. */
const collectionIds = new Set(
  collections.flatMap((c) => c.charms).map((label) => label),
);
const listedIds = [...(list.matchAll(/\[\s*"([A-Za-z0-9]+)"\s*,\s*"/g))].map((m) => m[1]);
const seasonal = complete.filter((n) => !listedIds.includes(n)).sort();

writeFileSync(
  join(root, "src/data/stats.generated.ts"),
  `// Generated by scripts/generate-stats.mjs. Do not edit — change the source data.\n` +
    `export type CharmCollection = { name: string; description: string; charms: string[] };\n\n` +
    `/** Collections and their charms, read from the component that renders them. */\n` +
    `export const COLLECTIONS: CharmCollection[] = ${JSON.stringify(collections, null, 2)};\n\n` +
    `/**\n` +
    ` * The number to quote. Every charm whose artwork ships complete — both the\n` +
    ` * plain drawing and the connected one with the thread attached.\n` +
    ` *\n` +
    ` * This is the honest public figure. It is not the collection total: twenty\n` +
    ` * seasonal and lucky charms ship without belonging to a named collection.\n` +
    ` */\n` +
    `export const CHARM_TOTAL = ${artwork.complete};\n\n` +
    `/** Charms named across the ${collections.length} collections on the product page. */\n` +
    `export const CHARM_IN_COLLECTIONS = ${charmTotal};\n\n` +
    `/** Collections on the product page. */\n` +
    `export const COLLECTION_COUNT = ${collections.length};\n\n` +
    `/** Seasonal and lucky charms that belong to no collection. */\n` +
    `export const SEASONAL = ${JSON.stringify(seasonal, null, 2)};\n\n` +
    `export const SEASONAL_COUNT = ${seasonal.length};\n\n` +
    `/** Deprecated alias. Prefer CHARM_IN_COLLECTIONS, or CHARM_TOTAL to quote. */\n` +
    `export const CHARM_COUNT = ${charmTotal};\n\n` +
    `export const ARTWORK = ${JSON.stringify(artwork)};\n\n` +
    `export const RELEASE = ${JSON.stringify({ macOS, windows }, null, 2)};\n\n` +
    `export const GENERATED_AT = ${JSON.stringify(new Date().toISOString().slice(0, 10))};\n`,
  "utf8",
);
/* ── guard: no hand-written charm count may come back ──────────────────────
   "80+" spread to twenty-odd files by hand and survived months of edits
   because nothing checked it. Counting is only half the fix; the other half
   is making the old habit fail loudly. */
// No trailing \b: it sits after "+" in "80+", where both sides are non-word
// characters, so the boundary never matches and the guard silently passes.
const FORBIDDEN = /80\+\s*charms|\b(?:over|Over)\s+eighty\s+charms|\beighty-plus\s+charms|value:\s*['"`]80\+/;
const offenders = [];
const scan = (dir) => {
  for (const entry of readdirSync(join(root, dir), { withFileTypes: true })) {
    const rel = `${dir}/${entry.name}`;
    if (entry.isDirectory()) { scan(rel); continue; }
    if (!/\.tsx?$/.test(entry.name)) continue;
    // The verification register documents the old claim on purpose.
    if (rel.includes("verification/claims.ts")) continue;
    const text = readFileSync(join(root, rel), "utf8");
    if (FORBIDDEN.test(text)) offenders.push(rel);
  }
};
scan("src");
if (offenders.length) {
  console.error(
    `\n  generate-stats: a hand-written charm count is back in:\n` +
      offenders.map((o) => `    ${o}`).join("\n") +
      `\n\n  Import CHARM_TOTAL from @/data/stats.generated instead, or write the\n` +
      `  figure as prose that matches it (${artwork.complete}).\n`,
  );
  process.exit(1);
}

console.log(
  `  stats: ${artwork.complete} charms complete (${charmTotal} in ${collections.length} collections ` +
    `+ ${seasonal.length} seasonal), macOS ${macOS.version}, Windows ${windows}`,
);
