/**
 * Every charm Hangly ships, and everything the repository actually knows
 * about it.
 *
 * This is the single source of truth. Pages, filters, schema, the sitemap and
 * the archive all derive from here, and nothing may hardcode a charm list.
 *
 * **The honest-unknown contract.** A field is `null` when the answer is not
 * recorded anywhere, and `null` is never quietly treated as a default. Of the
 * 75 charms, 20 have no display name in this codebase — they exist only as
 * `manekiNeko.svg` and similar — and no charm has an authored description,
 * meaning or source. Those gaps are real and are reported by
 * `scripts/validate-charm-registry.mjs` rather than filled in with plausible
 * text. A page that needs a meaning must wait for one to be written, because a
 * guessed meaning for a cultural object is worse than an absent one.
 *
 * **Provenance is recorded, not assumed.** `categorySource` and `seasonSource`
 * say where a classification came from. "collection" means it was read from
 * Collections.tsx. "inferred-from-id" means it was deduced from the filename —
 * `pumpkin` is almost certainly Halloween, but almost certainly is not the same
 * as recorded, and a reader of this file should be able to tell the difference.
 *
 * **`licensed` is a safety flag, not a category.** It marks charms that are
 * somebody else's intellectual property, and it exists so that no template can
 * ever generate an indexed landing page targeting a trademark. Eight of the
 * eleven collections are licensed. Treat an uncertain charm as licensed: the
 * cost of being wrong in that direction is a page that does not exist.
 */

export type CharmCategory =
  | "protection"
  | "cultural"
  | "mythology"
  | "luck"
  | "seasonal"
  | "symbol"
  | "character"
  | "unknown";

export type CharmSeason = "halloween" | "winter" | "diwali";

/** Where a classification came from. `unknown` means nothing recorded it. */
export type Provenance = "collection" | "inferred-from-id" | "authored" | "unknown";

export type Charm = {
  /** Matches the artwork filename. The join key for everything. */
  id: string;
  /** Human-readable name. `null` for the 20 charms nothing has ever named. */
  displayName: string | null;
  /** Collection from Collections.tsx, or `null` when it belongs to none. */
  collection: string | null;
  category: CharmCategory;
  categorySource: Provenance;
  season: CharmSeason | null;
  seasonSource: Provenance;
  /** Someone else's IP. Blocks indexable page generation. */
  licensed: boolean;
  /** One paragraph. `null` until written — never generated. */
  description: string | null;
  /** What the charm means in its tradition. `null` until sourced. */
  meaning: string | null;
  /** Where `meaning` came from. Empty until there is something to cite. */
  sourceUrls: string[];
  artworkPath: string;
  /** The rendering with the thread attached. `null` if it does not exist. */
  connectedArtworkPath: string | null;
};

export const CHARMS: Charm[] = [
  {
    id: "bat",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: "halloween",
    seasonSource: "inferred-from-id",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/bat.svg",
    connectedArtworkPath: "/charms/connected/bat.svg",
  },
  {
    id: "batmanSymbol",
    displayName: "Batman",
    collection: "DC",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/batmanSymbol.svg",
    connectedArtworkPath: "/charms/connected/batmanSymbol.svg",
  },
  {
    id: "bell",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/bell.svg",
    connectedArtworkPath: "/charms/connected/bell.svg",
  },
  {
    id: "breakingBad1",
    displayName: "Walter White",
    collection: "Breaking Bad",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/breakingBad1.svg",
    connectedArtworkPath: "/charms/connected/breakingBad1.svg",
  },
  {
    id: "breakingBad2",
    displayName: "Jesse Pinkman",
    collection: "Breaking Bad",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/breakingBad2.svg",
    connectedArtworkPath: "/charms/connected/breakingBad2.svg",
  },
  {
    id: "breakingBad3",
    displayName: "Saul Goodman",
    collection: "Breaking Bad",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/breakingBad3.svg",
    connectedArtworkPath: "/charms/connected/breakingBad3.svg",
  },
  {
    id: "breakingBad4",
    displayName: "Gus Fring",
    collection: "Breaking Bad",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/breakingBad4.svg",
    connectedArtworkPath: "/charms/connected/breakingBad4.svg",
  },
  {
    id: "breakingBad5",
    displayName: "Mike Ehrmantraut",
    collection: "Breaking Bad",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/breakingBad5.svg",
    connectedArtworkPath: "/charms/connected/breakingBad5.svg",
  },
  {
    id: "breakingBad6",
    displayName: "Heisenberg",
    collection: "Breaking Bad",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/breakingBad6.svg",
    connectedArtworkPath: "/charms/connected/breakingBad6.svg",
  },
  {
    id: "breakingBad7",
    displayName: "The RV",
    collection: "Breaking Bad",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/breakingBad7.svg",
    connectedArtworkPath: "/charms/connected/breakingBad7.svg",
  },
  {
    id: "btsMemberFive",
    displayName: "Jimin",
    collection: "BTS",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/btsMemberFive.svg",
    connectedArtworkPath: "/charms/connected/btsMemberFive.svg",
  },
  {
    id: "btsMemberFour",
    displayName: "RM",
    collection: "BTS",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/btsMemberFour.svg",
    connectedArtworkPath: "/charms/connected/btsMemberFour.svg",
  },
  {
    id: "btsMemberOne",
    displayName: "Jin",
    collection: "BTS",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/btsMemberOne.svg",
    connectedArtworkPath: "/charms/connected/btsMemberOne.svg",
  },
  {
    id: "btsMemberSeven",
    displayName: "Jung Kook",
    collection: "BTS",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/btsMemberSeven.svg",
    connectedArtworkPath: "/charms/connected/btsMemberSeven.svg",
  },
  {
    id: "btsMemberSix",
    displayName: "V",
    collection: "BTS",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/btsMemberSix.svg",
    connectedArtworkPath: "/charms/connected/btsMemberSix.svg",
  },
  {
    id: "btsMemberThree",
    displayName: "J-Hope",
    collection: "BTS",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/btsMemberThree.svg",
    connectedArtworkPath: "/charms/connected/btsMemberThree.svg",
  },
  {
    id: "btsMemberTwo",
    displayName: "Suga",
    collection: "BTS",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/btsMemberTwo.svg",
    connectedArtworkPath: "/charms/connected/btsMemberTwo.svg",
  },
  {
    id: "candyCane",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: "winter",
    seasonSource: "inferred-from-id",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/candyCane.svg",
    connectedArtworkPath: "/charms/connected/candyCane.svg",
  },
  {
    id: "captainAmericaShield",
    displayName: "Captain America Shield",
    collection: "Marvel",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/captainAmericaShield.svg",
    connectedArtworkPath: "/charms/connected/captainAmericaShield.svg",
  },
  {
    id: "daruma",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/daruma.svg",
    connectedArtworkPath: "/charms/connected/daruma.svg",
  },
  {
    id: "diya",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: "diwali",
    seasonSource: "inferred-from-id",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/diya.svg",
    connectedArtworkPath: "/charms/connected/diya.svg",
  },
  {
    id: "dreamCatcher",
    displayName: "Dream Catcher",
    collection: "Dream Catcher",
    category: "cultural",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/dreamCatcher.svg",
    connectedArtworkPath: "/charms/connected/dreamCatcher.svg",
  },
  {
    id: "drishtiBommai",
    displayName: "Drishti Bommai",
    collection: "Protection",
    category: "protection",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/drishtiBommai.svg",
    connectedArtworkPath: "/charms/connected/drishtiBommai.svg",
  },
  {
    id: "firework",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: "diwali",
    seasonSource: "inferred-from-id",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/firework.svg",
    connectedArtworkPath: "/charms/connected/firework.svg",
  },
  {
    id: "flash",
    displayName: "Flash",
    collection: "DC",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/flash.svg",
    connectedArtworkPath: "/charms/connected/flash.svg",
  },
  {
    id: "football25",
    displayName: "Cristiano Ronaldo",
    collection: "Football",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/football25.svg",
    connectedArtworkPath: "/charms/connected/football25.svg",
  },
  {
    id: "football26",
    displayName: "Lionel Messi",
    collection: "Football",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/football26.svg",
    connectedArtworkPath: "/charms/connected/football26.svg",
  },
  {
    id: "football27",
    displayName: "Neymar Jr.",
    collection: "Football",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/football27.svg",
    connectedArtworkPath: "/charms/connected/football27.svg",
  },
  {
    id: "football28",
    displayName: "Real Madrid",
    collection: "Football",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/football28.svg",
    connectedArtworkPath: "/charms/connected/football28.svg",
  },
  {
    id: "football29",
    displayName: "FC Barcelona",
    collection: "Football",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/football29.svg",
    connectedArtworkPath: "/charms/connected/football29.svg",
  },
  {
    id: "friends14",
    displayName: "Rachel Green",
    collection: "Friends",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/friends14.svg",
    connectedArtworkPath: "/charms/connected/friends14.svg",
  },
  {
    id: "friends15",
    displayName: "Monica Geller",
    collection: "Friends",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/friends15.svg",
    connectedArtworkPath: "/charms/connected/friends15.svg",
  },
  {
    id: "friends16",
    displayName: "Ross Geller",
    collection: "Friends",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/friends16.svg",
    connectedArtworkPath: "/charms/connected/friends16.svg",
  },
  {
    id: "friends17",
    displayName: "Joey Tribbiani",
    collection: "Friends",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/friends17.svg",
    connectedArtworkPath: "/charms/connected/friends17.svg",
  },
  {
    id: "friends18",
    displayName: "Chandler Bing",
    collection: "Friends",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/friends18.svg",
    connectedArtworkPath: "/charms/connected/friends18.svg",
  },
  {
    id: "friends19",
    displayName: "Phoebe Buffay",
    collection: "Friends",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/friends19.svg",
    connectedArtworkPath: "/charms/connected/friends19.svg",
  },
  {
    id: "ghanta",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/ghanta.svg",
    connectedArtworkPath: "/charms/connected/ghanta.svg",
  },
  {
    id: "ghost",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: "halloween",
    seasonSource: "inferred-from-id",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/ghost.svg",
    connectedArtworkPath: "/charms/connected/ghost.svg",
  },
  {
    id: "greenLanternRing",
    displayName: "Green Lantern",
    collection: "DC",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/greenLanternRing.svg",
    connectedArtworkPath: "/charms/connected/greenLanternRing.svg",
  },
  {
    id: "hamsa",
    displayName: "Hamsa",
    collection: "Protection",
    category: "protection",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/hamsa.svg",
    connectedArtworkPath: "/charms/connected/hamsa.svg",
  },
  {
    id: "himmeli",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/himmeli.svg",
    connectedArtworkPath: "/charms/connected/himmeli.svg",
  },
  {
    id: "horseshoe",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/horseshoe.svg",
    connectedArtworkPath: "/charms/connected/horseshoe.svg",
  },
  {
    id: "hulkFist",
    displayName: "Hulk Fist",
    collection: "Marvel",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/hulkFist.svg",
    connectedArtworkPath: "/charms/connected/hulkFist.svg",
  },
  {
    id: "ironManHelmet",
    displayName: "Iron Man Helmet",
    collection: "Marvel",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/ironManHelmet.svg",
    connectedArtworkPath: "/charms/connected/ironManHelmet.svg",
  },
  {
    id: "karuppuStatue",
    displayName: "Karuppu",
    collection: "Tamil Divine",
    category: "mythology",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/karuppuStatue.svg",
    connectedArtworkPath: "/charms/connected/karuppuStatue.svg",
  },
  {
    id: "lantern",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: "diwali",
    seasonSource: "inferred-from-id",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/lantern.svg",
    connectedArtworkPath: "/charms/connected/lantern.svg",
  },
  {
    id: "lotus",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/lotus.svg",
    connectedArtworkPath: "/charms/connected/lotus.svg",
  },
  {
    id: "luckyCoin",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/luckyCoin.svg",
    connectedArtworkPath: "/charms/connected/luckyCoin.svg",
  },
  {
    id: "manekiNeko",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/manekiNeko.svg",
    connectedArtworkPath: "/charms/connected/manekiNeko.svg",
  },
  {
    id: "nazar",
    displayName: "Nazar / Evil Eye",
    collection: "Protection",
    category: "protection",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/nazar.svg",
    connectedArtworkPath: "/charms/connected/nazar.svg",
  },
  {
    id: "nimbuMirchi",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/nimbuMirchi.svg",
    connectedArtworkPath: "/charms/connected/nimbuMirchi.svg",
  },
  {
    id: "omSymbol",
    displayName: "Om",
    collection: "Tamil Divine",
    category: "mythology",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/omSymbol.svg",
    connectedArtworkPath: "/charms/connected/omSymbol.svg",
  },
  {
    id: "panchangJie",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/panchangJie.svg",
    connectedArtworkPath: "/charms/connected/panchangJie.svg",
  },
  {
    id: "pumpkin",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: "halloween",
    seasonSource: "inferred-from-id",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/pumpkin.svg",
    connectedArtworkPath: "/charms/connected/pumpkin.svg",
  },
  {
    id: "scarab",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/scarab.svg",
    connectedArtworkPath: "/charms/connected/scarab.svg",
  },
  {
    id: "shazamLightning",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/shazamLightning.svg",
    connectedArtworkPath: "/charms/connected/shazamLightning.svg",
  },
  {
    id: "singer20",
    displayName: "Billie Eilish",
    collection: "Singers",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/singer20.svg",
    connectedArtworkPath: "/charms/connected/singer20.svg",
  },
  {
    id: "singer21",
    displayName: "XXXTENTACION",
    collection: "Singers",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/singer21.svg",
    connectedArtworkPath: "/charms/connected/singer21.svg",
  },
  {
    id: "singer22",
    displayName: "Michael Jackson",
    collection: "Singers",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/singer22.svg",
    connectedArtworkPath: "/charms/connected/singer22.svg",
  },
  {
    id: "singer23",
    displayName: "Taylor Swift",
    collection: "Singers",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/singer23.svg",
    connectedArtworkPath: "/charms/connected/singer23.svg",
  },
  {
    id: "singer24",
    displayName: "Juice WRLD",
    collection: "Singers",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/singer24.svg",
    connectedArtworkPath: "/charms/connected/singer24.svg",
  },
  {
    id: "snowflake",
    displayName: null,
    collection: null,
    category: "unknown",
    categorySource: "unknown",
    season: "winter",
    seasonSource: "inferred-from-id",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/snowflake.svg",
    connectedArtworkPath: "/charms/connected/snowflake.svg",
  },
  {
    id: "spiderMan",
    displayName: "Spider-Man",
    collection: "Marvel",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/spiderMan.svg",
    connectedArtworkPath: "/charms/connected/spiderMan.svg",
  },
  {
    id: "strangerThings10",
    displayName: "Dustin Henderson",
    collection: "Stranger Things",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/strangerThings10.svg",
    connectedArtworkPath: "/charms/connected/strangerThings10.svg",
  },
  {
    id: "strangerThings11",
    displayName: "Lucas Sinclair",
    collection: "Stranger Things",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/strangerThings11.svg",
    connectedArtworkPath: "/charms/connected/strangerThings11.svg",
  },
  {
    id: "strangerThings12",
    displayName: "Will Byers",
    collection: "Stranger Things",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/strangerThings12.svg",
    connectedArtworkPath: "/charms/connected/strangerThings12.svg",
  },
  {
    id: "strangerThings13",
    displayName: "Demogorgon",
    collection: "Stranger Things",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/strangerThings13.svg",
    connectedArtworkPath: "/charms/connected/strangerThings13.svg",
  },
  {
    id: "strangerThings8",
    displayName: "Eleven",
    collection: "Stranger Things",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/strangerThings8.svg",
    connectedArtworkPath: "/charms/connected/strangerThings8.svg",
  },
  {
    id: "strangerThings9",
    displayName: "Mike Wheeler",
    collection: "Stranger Things",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/strangerThings9.svg",
    connectedArtworkPath: "/charms/connected/strangerThings9.svg",
  },
  {
    id: "supermanShield",
    displayName: "Superman",
    collection: "DC",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/supermanShield.svg",
    connectedArtworkPath: "/charms/connected/supermanShield.svg",
  },
  {
    id: "templeBell",
    displayName: "Temple Bell",
    collection: "Tamil Divine",
    category: "mythology",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/templeBell.svg",
    connectedArtworkPath: "/charms/connected/templeBell.svg",
  },
  {
    id: "thorHammer",
    displayName: "Thor Hammer",
    collection: "Marvel",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/thorHammer.svg",
    connectedArtworkPath: "/charms/connected/thorHammer.svg",
  },
  {
    id: "vel",
    displayName: "Vel",
    collection: "Tamil Divine",
    category: "mythology",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/vel.svg",
    connectedArtworkPath: "/charms/connected/vel.svg",
  },
  {
    id: "vinayagarCoin",
    displayName: "Vinayagar",
    collection: "Tamil Divine",
    category: "mythology",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: false,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/vinayagarCoin.svg",
    connectedArtworkPath: "/charms/connected/vinayagarCoin.svg",
  },
  {
    id: "wonderWomanEmblem",
    displayName: "Wonder Woman",
    collection: "DC",
    category: "character",
    categorySource: "collection",
    season: null,
    seasonSource: "unknown",
    licensed: true,
    description: null,
    meaning: null,
    sourceUrls: [],
    artworkPath: "/charms/wonderWomanEmblem.svg",
    connectedArtworkPath: "/charms/connected/wonderWomanEmblem.svg",
  },
];

/** Ids are the join key, so uniqueness is enforced rather than assumed. */
export const CHARM_IDS: readonly string[] = CHARMS.map((c) => c.id);

export function getCharm(id: string): Charm | undefined {
  return CHARMS.find((c) => c.id === id);
}
