#!/usr/bin/env python3
"""Draws the seasonal charms into Assets/Charms as SVG.

The eleven collection charms were illustrated by hand. These were constructed —
which is a different way of drawing, and the reason they are generated by a script
rather than exported from an editor: a snowflake's six-fold symmetry and a coin's
concentric rims are arithmetic, and arithmetic is better written down than clicked.

Everything here shares one style kit so the packs sit together and sit beside the
hand-drawn collection: light from the upper left, a dark contour under every shape,
a gradient fill over it, a specular highlight on top, and the collection's gold on
the cord and the beads. Re-run after editing, then Scripts/sync-charm-assets.sh.
"""

import pathlib
import sys

from charm_style_kit import (
    BODY_R, BODY_Y, CX, GOLD, GOLD_DARK, H, W,
    hanger, header, ramp, shaped, spark, three, write_all,
)
import math

# Where each charm's ink actually stops, measured from the rendered artwork rather
# than guessed from the path data — stroke widths and round caps reach past the
# coordinates that drew them. The collection's artwork fills its canvas to the
# bottom edge, and `CharmArtworkSplitterTests` enforces that, so each of these is
# trimmed to its own content instead of sharing one tall box with air underneath.
BOTTOM = {
    "Snowflake": 155.0, "Bell": 158.0, "Candy Cane": 157.0, "Pumpkin": 152.0,
    "Ghost": 156.0, "Bat": 130.5, "Diya": 150.0, "Lotus": 141.5,
    "Lantern": 162.0, "Firework": 158.0, "Lucky Coin": 152.0,
}


# ---------------------------------------------------------------- Christmas

def snowflake():
    contour, radius = "#10456a", 40.0
    arms = []
    for index in range(6):
        angle = math.radians(index * 60)
        ux, uy = math.sin(angle), -math.cos(angle)
        arms.append(f"M{CX:.2f},{BODY_Y:.2f}L{CX + ux * radius:.2f},{BODY_Y + uy * radius:.2f}")
        for station, span in ((0.40, 0.34), (0.68, 0.26)):
            bx, by = CX + ux * radius * station, BODY_Y + uy * radius * station
            for side in (-1, 1):
                branch = angle + side * math.radians(52)
                arms.append(
                    f"M{bx:.2f},{by:.2f}"
                    f"L{bx + math.sin(branch) * radius * span:.2f},"
                    f"{by - math.cos(branch) * radius * span:.2f}"
                )
    path = "".join(arms)
    defs = three("ice", ("#ffffff", "#a9dcf5", "#1f5f88")) \
        + three("iceBead", ("#ffffff", "#9fd6f2", "#215f86"), radial=True) \
        + three("core", ("#ffffff", "#bfe6fa", "#3e86b0"), radial=True)
    return header(defs) + hanger("url(#iceBead)", contour) + f"""  <g fill="none" stroke-linecap="round">
    <path d="{path}" stroke="{contour}" stroke-width="9.4"/>
    <path d="{path}" stroke="url(#ice)" stroke-width="6.6"/>
    <path d="{path}" stroke="#ffffff" stroke-width="1.9" opacity="0.55" transform="translate(-1.05,-1.05)"/>
  </g>
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="13.4" fill="{contour}"/>
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="11.6" fill="url(#gold)"/>
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="8.2" fill="{contour}"/>
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="7.1" fill="url(#core)"/>
  {spark(CX - 2.5, BODY_Y - 2.7, 3, 2.1, 0.9)}
</svg>
"""


def bell():
    contour = "#4a2c05"
    top, lip, half = 79.0, 140.0, 33.0
    # A bell is a shoulder, a waist that curves *outward*, and a lip that flares
    # past it — not a cone. The middle control points are what make the difference.
    body = (
        f"M{CX - 8:g},{top:g}"
        f"C{CX - 8:g},{top - 4:g} {CX + 8:g},{top - 4:g} {CX + 8:g},{top:g}"
        f"C{CX + 15:g},{top + 11:g} {CX + 19:g},{top + 28:g} {CX + 21:g},{lip - 22:g}"
        f"C{CX + 23:g},{lip - 10:g} {CX + 28:g},{lip - 8:g} {CX + half:g},{lip - 5:g}"
        f"C{CX + half + 1:g},{lip - 1:g} {CX + half - 3:g},{lip:g} {CX + half - 7:g},{lip:g}"
        f"L{CX - half + 7:g},{lip:g}"
        f"C{CX - half + 3:g},{lip:g} {CX - half - 1:g},{lip - 1:g} {CX - half:g},{lip - 5:g}"
        f"C{CX - 28:g},{lip - 8:g} {CX - 23:g},{lip - 10:g} {CX - 21:g},{lip - 22:g}"
        f"C{CX - 19:g},{top + 28:g} {CX - 15:g},{top + 11:g} {CX - 8:g},{top:g}Z"
    )
    defs = three("brass", ("#ffe6a6", "#d79a2b", "#6d3d06")) \
        + three("brassBead", ("#ffe6a6", "#d79a2b", "#6d3d06"), radial=True)
    return header(defs) + hanger("url(#brassBead)", contour) + f"""  <circle cx="{CX:g}" cy="{top - 9:g}" r="7.4" fill="none" stroke="{contour}" stroke-width="6.8"/>
  <circle cx="{CX:g}" cy="{top - 9:g}" r="7.4" fill="none" stroke="url(#gold)" stroke-width="4.4"/>
  {shaped(body, contour, "url(#brass)", 3.2)}
  <path d="M{CX - half + 9:g},{lip - 14:g}L{CX + half - 9:g},{lip - 14:g}" stroke="{contour}"
        stroke-width="4.6" fill="none" opacity="0.5"/>
  <path d="M{CX - half + 10:g},{lip - 14:g}L{CX + half - 10:g},{lip - 14:g}" stroke="#ffdf95"
        stroke-width="1.9" fill="none" opacity="0.55"/>
  <ellipse cx="{CX:g}" cy="{lip + 8:g}" rx="7.6" ry="7.6" fill="{contour}"/>
  <ellipse cx="{CX:g}" cy="{lip + 8:g}" rx="6.4" ry="6.4" fill="url(#brassBead)"/>
  <path d="M{CX - 13:g},{top + 12:g}C{CX - 17:g},{top + 30:g} {CX - 19:g},{lip - 28:g} {CX - 21:g},{lip - 14:g}"
        stroke="#ffffff" stroke-width="3.6" fill="none" opacity="0.42" stroke-linecap="round"/>
</svg>
"""


def candy_cane():
    contour = "#5e0b06"
    hook = (
        f"M{CX + 11:g},{BODY_Y + 38:g}"
        f"L{CX + 11:g},{BODY_Y - 14:g}"
        f"A15,15 0 0 0 {CX - 19:g},{BODY_Y - 14:g}"
    )
    defs = three("candyBead", ("#ffb3a6", "#e0281c", "#5e0b06"), radial=True)
    return header(defs) + hanger("url(#candyBead)", contour) + f"""  <g fill="none" stroke-linecap="round">
    <path d="{hook}" stroke="{contour}" stroke-width="17"/>
    <path d="{hook}" stroke="#fdfdfb" stroke-width="13.4"/>
    <path d="{hook}" stroke="#e0281c" stroke-width="13.4"
          stroke-dasharray="6.5 9.5" stroke-linecap="butt"/>
    <path d="{hook}" stroke="#ffffff" stroke-width="3" opacity="0.5"
          transform="translate(-2.4,-2.4)"/>
    <path d="{hook}" stroke="{contour}" stroke-width="2.4" opacity="0.22"
          transform="translate(2.6,2.6)"/>
  </g>
</svg>
"""


# ---------------------------------------------------------------- Halloween

def pumpkin():
    contour, top, bottom = "#5b2404", 82.0, 148.0
    mid = (top + bottom) / 2
    def lobe(offset, width):
        return (
            f"M{CX + offset:g},{top:g}"
            f"C{CX + offset - width:g},{top + 4:g} {CX + offset - width:g},{bottom - 4:g} {CX + offset:g},{bottom:g}"
            f"C{CX + offset + width:g},{bottom - 4:g} {CX + offset + width:g},{top + 4:g} {CX + offset:g},{top:g}Z"
        )
    body = lobe(0, 30)
    eye_l = f"M{CX - 19:g},{mid - 6:g}L{CX - 7:g},{mid + 1:g}L{CX - 19:g},{mid + 5:g}Z"
    eye_r = f"M{CX + 19:g},{mid - 6:g}L{CX + 7:g},{mid + 1:g}L{CX + 19:g},{mid + 5:g}Z"
    mouth = (
        f"M{CX - 20:g},{mid + 12:g}L{CX - 13:g},{mid + 19:g}L{CX - 7:g},{mid + 13:g}"
        f"L{CX:g},{mid + 20:g}L{CX + 7:g},{mid + 13:g}L{CX + 13:g},{mid + 19:g}"
        f"L{CX + 20:g},{mid + 12:g}L{CX + 15:g},{mid + 25:g}L{CX - 15:g},{mid + 25:g}Z"
    )
    defs = three("gourd", ("#ffc46b", "#ef7a16", "#8e3403")) \
        + three("gourdBead", ("#ffc46b", "#ef7a16", "#8e3403"), radial=True) \
        + three("stalk", ("#9ad06a", "#3f7a24", "#1b3a0d")) \
        + ramp("glow", ((0, "#fff3c4"), (0.5, "#ffc531"), (1, "#ff8a1e")))
    return header(defs) + hanger("url(#gourdBead)", contour) + f"""  {shaped(body, contour, "url(#gourd)", 3.4)}
  {shaped(lobe(-16, 14), contour, "url(#gourd)", 2.2)}
  {shaped(lobe(16, 14), contour, "url(#gourd)", 2.2)}
  <path d="M{CX:g},{top + 1:g}C{CX - 3:g},{top - 9:g} {CX + 6:g},{top - 13:g} {CX + 3:g},{top - 18:g}"
        stroke="{contour}" stroke-width="9" fill="none" stroke-linecap="round"/>
  <path d="M{CX:g},{top + 1:g}C{CX - 3:g},{top - 9:g} {CX + 6:g},{top - 13:g} {CX + 3:g},{top - 18:g}"
        stroke="url(#stalk)" stroke-width="6" fill="none" stroke-linecap="round"/>
  <g fill="url(#glow)" stroke="{contour}" stroke-width="1.6" stroke-linejoin="round">
    <path d="{eye_l}"/><path d="{eye_r}"/><path d="{mouth}"/>
  </g>
  <path d="M{CX - 21:g},{top + 16:g}C{CX - 26:g},{mid:g} {CX - 25:g},{mid + 16:g} {CX - 19:g},{bottom - 12:g}"
        stroke="#ffffff" stroke-width="3.6" fill="none" opacity="0.34" stroke-linecap="round"/>
</svg>
"""


def ghost():
    contour, top, hem = "#3b4468", 74.0, 145.0
    body = (
        f"M{CX - 28:g},{hem - 6:g}"
        f"C{CX - 30:g},{top + 16:g} {CX - 20:g},{top:g} {CX:g},{top:g}"
        f"C{CX + 20:g},{top:g} {CX + 30:g},{top + 16:g} {CX + 28:g},{hem - 6:g}"
        f"C{CX + 24:g},{hem + 6:g} {CX + 20:g},{hem - 8:g} {CX + 14:g},{hem + 3:g}"
        f"C{CX + 9:g},{hem + 11:g} {CX + 5:g},{hem - 6:g} {CX:g},{hem + 4:g}"
        f"C{CX - 5:g},{hem + 12:g} {CX - 9:g},{hem - 6:g} {CX - 14:g},{hem + 3:g}"
        f"C{CX - 20:g},{hem + 11:g} {CX - 24:g},{hem + 6:g} {CX - 28:g},{hem - 6:g}Z"
    )
    defs = three("linen", ("#ffffff", "#dfe4f4", "#8f9ac4")) \
        + three("linenBead", ("#ffffff", "#dfe4f4", "#8f9ac4"), radial=True)
    return header(defs) + hanger("url(#linenBead)", contour) + f"""  {shaped(body, contour, "url(#linen)", 3.2)}
  <ellipse cx="{CX - 9:g}" cy="{top + 24:g}" rx="4.6" ry="6" fill="{contour}"/>
  <ellipse cx="{CX + 9:g}" cy="{top + 24:g}" rx="4.6" ry="6" fill="{contour}"/>
  <ellipse cx="{CX:g}" cy="{top + 40:g}" rx="5.4" ry="6.6" fill="{contour}" opacity="0.85"/>
  {spark(CX - 10.4, top + 21.6, 1.5, 1.9, 0.85)}
  {spark(CX + 7.6, top + 21.6, 1.5, 1.9, 0.85)}
  <path d="M{CX - 21:g},{top + 14:g}C{CX - 25:g},{top + 34:g} {CX - 24:g},{hem - 28:g} {CX - 21:g},{hem - 14:g}"
        stroke="#ffffff" stroke-width="4" fill="none" opacity="0.6" stroke-linecap="round"/>
</svg>
"""


def bat():
    contour, y = "#1e1330", BODY_Y - 4
    wing = (
        f"M{CX:g},{y - 4:g}"
        f"C{CX - 8:g},{y - 14:g} {CX - 16:g},{y - 17:g} {CX - 23:g},{y - 11:g}"
        f"C{CX - 20:g},{y - 3:g} {CX - 21:g},{y + 6:g} {CX - 24:g},{y + 13:g}"
        f"C{CX - 18:g},{y + 11:g} {CX - 15:g},{y + 16:g} {CX - 16:g},{y + 27:g}"
        f"C{CX - 13:g},{y + 17:g} {CX - 9:g},{y + 15:g} {CX - 5:g},{y + 16:g}Z"
    )
    defs = three("fur", ("#6b4c9e", "#3a2360", "#160d28")) \
        + three("furBead", ("#a789dd", "#4a2f7c", "#1b1032"), radial=True) \
        + three("membrane", ("#8f6fc8", "#4a2d7d", "#1d1136"))
    return header(defs) + hanger("url(#furBead)", contour) + f"""  {shaped(wing, contour, "url(#membrane)", 2.6)}
  <g transform="translate({W:g},0) scale(-1,1)">{shaped(wing, contour, "url(#membrane)", 2.6)}</g>
  {shaped(f"M{CX - 8:g},{y - 14:g}L{CX - 11:g},{y - 25:g}L{CX - 3:g},{y - 18:g}Z", contour, "url(#fur)", 2)}
  {shaped(f"M{CX + 8:g},{y - 14:g}L{CX + 11:g},{y - 25:g}L{CX + 3:g},{y - 18:g}Z", contour, "url(#fur)", 2)}
  <ellipse cx="{CX:g}" cy="{y + 2:g}" rx="11" ry="22" fill="{contour}"/>
  <ellipse cx="{CX:g}" cy="{y + 2:g}" rx="9.2" ry="20" fill="url(#fur)"/>
  <ellipse cx="{CX - 4:g}" cy="{y - 7:g}" rx="2.5" ry="3" fill="#ffd964"/>
  <ellipse cx="{CX + 4:g}" cy="{y - 7:g}" rx="2.5" ry="3" fill="#ffd964"/>
  <ellipse cx="{CX - 4:g}" cy="{y - 6.6:g}" rx="1.1" ry="1.5" fill="{contour}"/>
  <ellipse cx="{CX + 4:g}" cy="{y - 6.6:g}" rx="1.1" ry="1.5" fill="{contour}"/>
  {spark(CX - 3.4, y - 11, 2.4, 1.5, 0.5)}
</svg>
"""


# ------------------------------------------------------------------- Diwali

def diya():
    contour, rim, base = "#4d1d05", 120.0, 142.0
    bowl = (
        f"M{CX - 34:g},{rim:g}"
        f"C{CX - 32:g},{base - 2:g} {CX - 18:g},{base + 4:g} {CX:g},{base + 4:g}"
        f"C{CX + 18:g},{base + 4:g} {CX + 32:g},{base - 2:g} {CX + 34:g},{rim:g}Z"
    )
    flame = (
        f"M{CX:g},{rim - 46:g}"
        f"C{CX + 11:g},{rim - 32:g} {CX + 13:g},{rim - 18:g} {CX + 6:g},{rim - 9:g}"
        f"C{CX + 2:g},{rim - 4:g} {CX - 2:g},{rim - 4:g} {CX - 6:g},{rim - 9:g}"
        f"C{CX - 13:g},{rim - 18:g} {CX - 11:g},{rim - 32:g} {CX:g},{rim - 46:g}Z"
    )
    defs = three("clay", ("#e8a45f", "#b4571c", "#5c2205")) \
        + three("clayBead", ("#f0b878", "#b4571c", "#5c2205"), radial=True) \
        + ramp("flame", ((0, "#fff7cd"), (0.38, "#ffce3d"), (0.72, "#ff8a12"), (1, "#e0400c")), radial=True) \
        + ramp("halo", ((0, "#ffd46a"), (0.55, "#ff9c2a"), (1, "#ff8a1e")), radial=True)
    return header(defs) + hanger("url(#clayBead)", contour) + f"""  <ellipse cx="{CX:g}" cy="{rim - 22:g}" rx="26" ry="26" fill="url(#halo)" opacity="0.3"/>
  {shaped(flame, "#c8480d", "url(#flame)", 1.6)}
  <ellipse cx="{CX:g}" cy="{rim - 16:g}" rx="3.6" ry="7" fill="#fffbe4" opacity="0.85"/>
  {shaped(bowl, contour, "url(#clay)", 3.2)}
  <path d="M{CX - 34:g},{rim:g}L{CX + 34:g},{rim:g}" stroke="{contour}" stroke-width="5.4"
        stroke-linecap="round"/>
  <path d="M{CX - 32:g},{rim:g}L{CX + 32:g},{rim:g}" stroke="url(#gold)" stroke-width="3"
        stroke-linecap="round"/>
  <path d="M{CX - 24:g},{rim + 9:g}C{CX - 20:g},{base - 1:g} {CX - 12:g},{base + 2:g} {CX - 6:g},{base + 2:g}"
        stroke="#ffffff" stroke-width="3.2" fill="none" opacity="0.3" stroke-linecap="round"/>
</svg>
"""


def lotus():
    contour = "#7a1848"
    def petal(angle_deg, length, width):
        angle = math.radians(angle_deg)
        ux, uy = math.sin(angle), -math.cos(angle)
        px, py = -uy, ux
        tip = (CX + ux * length, BODY_Y + uy * length)
        left = (CX + px * width, BODY_Y + py * width)
        right = (CX - px * width, BODY_Y - py * width)
        return (
            f"M{CX:.2f},{BODY_Y:.2f}"
            f"C{left[0]:.2f},{left[1]:.2f} {tip[0] + px * width * 0.5:.2f},{tip[1] + py * width * 0.5:.2f} {tip[0]:.2f},{tip[1]:.2f}"
            f"C{tip[0] - px * width * 0.5:.2f},{tip[1] - py * width * 0.5:.2f} {right[0]:.2f},{right[1]:.2f} {CX:.2f},{BODY_Y:.2f}Z"
        )
    back = "".join(
        shaped(petal(angle, 40, 11), contour, "url(#petalBack)", 2.2)
        for angle in (-58, -29, 0, 29, 58)
    )
    front = "".join(
        shaped(petal(angle, 30, 10), contour, "url(#petal)", 2.2)
        for angle in (-42, -14, 14, 42)
    )
    defs = three("petal", ("#ffe3ef", "#f06aa6", "#a31f5e")) \
        + three("petalBack", ("#ffc9de", "#d94a8c", "#7a1848")) \
        + three("petalBead", ("#ffe3ef", "#f06aa6", "#a31f5e"), radial=True) \
        + three("seed", ("#fff2c4", "#e8bb46", "#8a6412"), radial=True)
    return header(defs) + hanger("url(#petalBead)", contour) + f"""  {back}
  {front}
  <path d="M{CX:g},{BODY_Y + 4:g}L{CX:g},{BODY_Y + 30:g}" stroke="#2f6b2a" stroke-width="6.4"
        stroke-linecap="round"/>
  <path d="M{CX:g},{BODY_Y + 6:g}L{CX:g},{BODY_Y + 29:g}" stroke="#5aa04a" stroke-width="3.4"
        stroke-linecap="round"/>
  <ellipse cx="{CX:g}" cy="{BODY_Y - 2:g}" rx="9.4" ry="7.4" fill="{contour}"/>
  <ellipse cx="{CX:g}" cy="{BODY_Y - 2:g}" rx="8" ry="6.2" fill="url(#seed)"/>
  {spark(CX - 2.6, BODY_Y - 4, 2.6, 1.7, 0.8)}
</svg>
"""


def lantern():
    contour, top, bottom, half = "#5c0c0c", 76.0, 138.0, 27.0
    body = (
        f"M{CX - half + 6:g},{top:g}L{CX + half - 6:g},{top:g}"
        f"C{CX + half + 3:g},{top + 18:g} {CX + half + 3:g},{bottom - 18:g} {CX + half - 6:g},{bottom:g}"
        f"L{CX - half + 6:g},{bottom:g}"
        f"C{CX - half - 3:g},{bottom - 18:g} {CX - half - 3:g},{top + 18:g} {CX - half + 6:g},{top:g}Z"
    )
    ribs = "".join(
        f'<path d="M{CX + offset:g},{top + 3:g}C{CX + offset * 1.34:g},{top + 22:g} '
        f'{CX + offset * 1.34:g},{bottom - 22:g} {CX + offset:g},{bottom - 3:g}" '
        f'stroke="#8d1616" stroke-width="1.7" fill="none" opacity="0.65"/>'
        for offset in (-12, 0, 12)
    )
    defs = three("silk", ("#ff9b86", "#d8221d", "#68100c")) \
        + three("silkBead", ("#ff9b86", "#d8221d", "#68100c"), radial=True) \
        + ramp("lit", ((0, "#fff0b4"), (1, "#ffb43c")), radial=True)
    return header(defs) + hanger("url(#silkBead)", contour) + f"""  <ellipse cx="{CX:g}" cy="{(top + bottom) / 2:g}" rx="34" ry="34" fill="url(#lit)" opacity="0.2"/>
  {shaped(body, contour, "url(#silk)", 3.2)}
  {ribs}
  <rect x="{CX - half - 1:g}" y="{top - 7:g}" width="{(half + 1) * 2:g}" height="8" rx="2.6" fill="{contour}"/>
  <rect x="{CX - half:g}" y="{top - 6:g}" width="{half * 2:g}" height="6" rx="2" fill="url(#gold)"/>
  <rect x="{CX - half - 1:g}" y="{bottom - 1:g}" width="{(half + 1) * 2:g}" height="8" rx="2.6" fill="{contour}"/>
  <rect x="{CX - half:g}" y="{bottom:g}" width="{half * 2:g}" height="6" rx="2" fill="url(#gold)"/>
  <path d="M{CX:g},{bottom + 7:g}L{CX:g},{bottom + 19:g}" stroke="{contour}" stroke-width="4.4"
        stroke-linecap="round"/>
  <path d="M{CX:g},{bottom + 7:g}L{CX:g},{bottom + 18:g}" stroke="url(#gold)" stroke-width="2.6"
        stroke-linecap="round"/>
  <path d="M{CX - 18:g},{top + 10:g}C{CX - 23:g},{top + 28:g} {CX - 23:g},{bottom - 26:g} {CX - 18:g},{bottom - 10:g}"
        stroke="#ffffff" stroke-width="3.4" fill="none" opacity="0.34" stroke-linecap="round"/>
</svg>
"""


# ----------------------------------------------------------------- New Year

def firework():
    contour = "#2a1155"
    rays, sparks = [], []
    for index in range(12):
        angle = math.radians(index * 30)
        ux, uy = math.sin(angle), -math.cos(angle)
        inner, outer = 8.0, 39.0 if index % 2 == 0 else 29.0
        rays.append(
            f"M{CX + ux * inner:.2f},{BODY_Y + uy * inner:.2f}"
            f"L{CX + ux * outer:.2f},{BODY_Y + uy * outer:.2f}"
        )
        dot = outer + 5.5
        sparks.append(
            f'<circle cx="{CX + ux * dot:.2f}" cy="{BODY_Y + uy * dot:.2f}" '
            f'r="{2.9 if index % 2 == 0 else 2.2:g}" fill="url(#gold)" '
            f'stroke="{contour}" stroke-width="1.1"/>'
        )
    path = "".join(rays)
    defs = three("burst", ("#fff6cf", "#ffc23c", "#c9600a")) \
        + three("burstBead", ("#fff6cf", "#ffc23c", "#8a3f06"), radial=True) \
        + three("heart", ("#ffffff", "#ffd865", "#d47a09"), radial=True)
    return header(defs) + hanger("url(#burstBead)", contour) + f"""  <g fill="none" stroke-linecap="round">
    <path d="{path}" stroke="{contour}" stroke-width="7.4"/>
    <path d="{path}" stroke="url(#burst)" stroke-width="4.8"/>
    <path d="{path}" stroke="#ffffff" stroke-width="1.5" opacity="0.45" transform="translate(-0.9,-0.9)"/>
  </g>
  {"".join(sparks)}
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="11.4" fill="{contour}"/>
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="9.6" fill="url(#heart)"/>
  {spark(CX - 3, BODY_Y - 3.2, 3.2, 2.2, 0.9)}
</svg>
"""


def lucky_coin():
    contour, radius, hole = "#5a3c06", 36.0, 9.4
    # Four marks around the hole, where a cash coin carries its four characters.
    # Struck rather than written: horizontal bars with one vertical through them,
    # which is what the glyphs read as at the size a charm is ever seen.
    marks = "".join(
        f'<g transform="translate({CX + dx:g},{BODY_Y + dy:g})" stroke="{contour}" '
        f'stroke-width="1.9" stroke-linecap="round" opacity="0.8" fill="none">'
        f'<path d="M-5,-4.6L5,-4.6M-5.8,0L5.8,0M-5,4.6L5,4.6M0,-6.4L0,6.4"/></g>'
        for dx, dy in ((0, -20), (0, 20), (-20, 0), (20, 0))
    )
    defs = three("coin", ("#fff3c0", "#dcae3a", "#7c5409")) \
        + three("coinBead", ("#fff3c0", "#dcae3a", "#7c5409"), radial=True) \
        + three("knot", ("#ff9b86", "#d8221d", "#68100c"))
    return header(defs) + hanger("url(#coinBead)", contour, cord_to=60) + f"""  <path d="M{CX:g},59L{CX:g},{BODY_Y - radius + 4:g}" stroke="#68100c" stroke-width="5.4"/>
  <path d="M{CX:g},59L{CX:g},{BODY_Y - radius + 4:g}" stroke="url(#knot)" stroke-width="3.4"/>
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="{radius:g}" fill="{contour}"/>
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="{radius - 2.2:g}" fill="url(#coin)"/>
  <circle cx="{CX:g}" cy="{BODY_Y:g}" r="{radius - 7:g}" fill="none" stroke="{contour}"
          stroke-width="1.8" opacity="0.6"/>
  {marks}
  <rect x="{CX - hole:g}" y="{BODY_Y - hole:g}" width="{hole * 2:g}" height="{hole * 2:g}"
        rx="1.6" fill="{contour}"/>
  <rect x="{CX - hole + 2:g}" y="{BODY_Y - hole + 2:g}" width="{(hole - 2) * 2:g}"
        height="{(hole - 2) * 2:g}" rx="1" fill="#3a2704"/>
  <circle cx="{CX:g}" cy="{BODY_Y + radius + 5:g}" r="6.2" fill="#68100c"/>
  <circle cx="{CX:g}" cy="{BODY_Y + radius + 5:g}" r="5" fill="url(#knot)"/>
  <path d="M{CX - 24:g},{BODY_Y - 20:g}A32,32 0 0 0 {CX - 26:g},{BODY_Y + 12:g}"
        stroke="#ffffff" stroke-width="4" fill="none" opacity="0.4" stroke-linecap="round"/>
</svg>
"""


CHARMS = {
    "Snowflake": snowflake,
    "Bell": bell,
    "Candy Cane": candy_cane,
    "Pumpkin": pumpkin,
    "Ghost": ghost,
    "Bat": bat,
    "Diya": diya,
    "Lotus": lotus,
    "Lantern": lantern,
    "Firework": firework,
    "Lucky Coin": lucky_coin,
}


def main():
    write_all(CHARMS, BOTTOM, pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "Assets/Charms"))


if __name__ == "__main__":
    main()
