// Generated by scripts/generate-changelog.mjs from the Sparkle feeds. Do not edit.
export type Release = {
  product: "hangly" | "vision";
  name: string;
  platform: string;
  version: string;
  /** ISO date, or "" where the feed carries none. */
  date: string;
  minimumSystem: string;
  bytes: number;
  notes: { kind: "para" | "point"; text: string }[];
  notesUrl: string;
};

export const RELEASES: Release[] = [
  {
    "product": "hangly",
    "name": "Hangly",
    "platform": "macOS",
    "version": "2.3.1",
    "date": "2026-10-06",
    "minimumSystem": "14.0",
    "bytes": 84088723,
    "notes": [
      {
        "kind": "point",
        "text": "Messi joins Football Legends. Holding the number ten up to the crowd."
      },
      {
        "kind": "point",
        "text": "One rope through every charm. With two or three charms, the rope runs unbroken from charm to charm however hard they swing, and only the top charm wears beads."
      },
      {
        "kind": "point",
        "text": "Charms hang like real pendants. The rope meets each charm at its top or its ring, straight above it, and beads stay on the rope and clear of the charm."
      },
      {
        "kind": "point",
        "text": "Lift a charm and the rope reels in. No more folded or vanishing rope when you hold a charm up near the top of the screen."
      }
    ],
    "notesUrl": ""
  },
  {
    "product": "hangly",
    "name": "Hangly",
    "platform": "macOS",
    "version": "2.3.0",
    "date": "2026-10-04",
    "minimumSystem": "14.0",
    "bytes": 81624822,
    "notes": [
      {
        "kind": "point",
        "text": "Realistic ropes and chains. Every rope is drawn from real thread, leather, silk and metal, and chains hang a charm by their own last link."
      },
      {
        "kind": "point",
        "text": "Charms hang from their own rings. No gaps: the rope meets every charm, and ringed charms hang from a tiny jump ring."
      },
      {
        "kind": "point",
        "text": "Update in Background. When a new version is out, a card under the charm says what is new; one press and Hangly updates and restarts by itself."
      },
      {
        "kind": "point",
        "text": "News from the charm. New charms and collections pop up in glass under your charm, swing with it, and leave on their own."
      },
      {
        "kind": "point",
        "text": "A smoother Library, and a glow that takes each charm's own shape."
      }
    ],
    "notesUrl": ""
  },
  {
    "product": "hangly",
    "name": "Hangly",
    "platform": "macOS",
    "version": "2.2.0",
    "date": "2026-10-02",
    "minimumSystem": "14.0",
    "bytes": 81148821,
    "notes": [],
    "notesUrl": ""
  },
  {
    "product": "vision",
    "name": "Vision",
    "platform": "macOS",
    "version": "1.1",
    "date": "2026-09-16",
    "minimumSystem": "15.0",
    "bytes": 17851522,
    "notes": [],
    "notesUrl": "https://www.sharancreatedthis.in/products/vision/release-notes.html"
  },
  {
    "product": "hangly",
    "name": "Hangly",
    "platform": "Windows",
    "version": "2.3.1",
    "date": "",
    "minimumSystem": "10.0",
    "bytes": 0,
    "notes": [],
    "notesUrl": "https://github.com/SharanCreatedThis/Hangly-Windows/releases/tag/v2.3.1"
  }
];
