// Generated by scripts/generate-stats.mjs. Do not edit — change the source data.
export type CharmCollection = { name: string; description: string; charms: string[] };

/** Collections and their charms, read from the component that renders them. */
export const COLLECTIONS: CharmCollection[] = [
  {
    "name": "Protection",
    "description": "A little luck. A little protection. A feeling of home.",
    "charms": [
      "Nazar / Evil Eye",
      "Drishti Bommai",
      "Hamsa"
    ]
  },
  {
    "name": "Marvel",
    "description": "For the hero behind the screen.",
    "charms": [
      "Spider-Man",
      "Captain America Shield",
      "Iron Man Helmet",
      "Thor Hammer",
      "Hulk Fist"
    ]
  },
  {
    "name": "DC",
    "description": "Iconic symbols. Extraordinary company.",
    "charms": [
      "Batman",
      "Superman",
      "Wonder Woman",
      "Flash",
      "Green Lantern"
    ]
  },
  {
    "name": "Tamil Divine",
    "description": "Sacred symbols. Familiar stories. Close to home.",
    "charms": [
      "Vel",
      "Vinayagar",
      "Om",
      "Karuppu",
      "Temple Bell"
    ]
  },
  {
    "name": "BTS",
    "description": "A little purple in your everyday.",
    "charms": [
      "Jin",
      "Suga",
      "J-Hope",
      "RM",
      "Jimin",
      "V",
      "Jung Kook"
    ]
  },
  {
    "name": "Football",
    "description": "A little piece of match day, always within reach.",
    "charms": [
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Neymar Jr.",
      "Real Madrid",
      "FC Barcelona"
    ]
  },
  {
    "name": "Stranger Things",
    "description": "For late-night mysteries and the bravest of friends.",
    "charms": [
      "Eleven",
      "Mike Wheeler",
      "Dustin Henderson",
      "Lucas Sinclair",
      "Will Byers",
      "Demogorgon"
    ]
  },
  {
    "name": "Singers",
    "description": "A little music for every moment on your desktop.",
    "charms": [
      "Billie Eilish",
      "XXXTENTACION",
      "Michael Jackson",
      "Taylor Swift",
      "Juice WRLD"
    ]
  },
  {
    "name": "Breaking Bad",
    "description": "A little danger. A lot of story.",
    "charms": [
      "Walter White",
      "Jesse Pinkman",
      "Saul Goodman",
      "Gus Fring",
      "Mike Ehrmantraut",
      "Heisenberg",
      "The RV"
    ]
  },
  {
    "name": "Friends",
    "description": "The one with your favorite everyday keepsakes.",
    "charms": [
      "Rachel Green",
      "Monica Geller",
      "Ross Geller",
      "Joey Tribbiani",
      "Chandler Bing",
      "Phoebe Buffay"
    ]
  },
  {
    "name": "Dream Catcher",
    "description": "A quiet little talisman for your day.",
    "charms": [
      "Dream Catcher"
    ]
  }
];

/**
 * The number to quote. Every charm whose artwork ships complete — both the
 * plain drawing and the connected one with the thread attached.
 *
 * This is the honest public figure. It is not the collection total: twenty
 * seasonal and lucky charms ship without belonging to a named collection.
 */
export const CHARM_TOTAL = 81;

/** Categories in the shipped catalogue, with their sizes. */
export const SHIPPED_CATEGORIES = [
  {
    "id": "protection",
    "name": "Protection",
    "charms": 6
  },
  {
    "id": "luck",
    "name": "Luck & Fortune",
    "charms": 4
  },
  {
    "id": "ritual",
    "name": "Ritual & Home",
    "charms": 2
  },
  {
    "id": "classic",
    "name": "Classic",
    "charms": 5
  },
  {
    "id": "seasonal",
    "name": "Seasonal",
    "charms": 11
  },
  {
    "id": "marvel",
    "name": "Marvel",
    "charms": 6
  },
  {
    "id": "dc",
    "name": "DC",
    "charms": 5
  },
  {
    "id": "tamilSpiritual",
    "name": "Tamil Spiritual",
    "charms": 5
  },
  {
    "id": "bts",
    "name": "BTS",
    "charms": 7
  },
  {
    "id": "footballLegends",
    "name": "Football Legends",
    "charms": 5
  },
  {
    "id": "musicLegends",
    "name": "Music Legends",
    "charms": 6
  },
  {
    "id": "friends",
    "name": "Friends",
    "charms": 6
  },
  {
    "id": "breakingBad",
    "name": "Breaking Bad",
    "charms": 7
  },
  {
    "id": "strangerThings",
    "name": "Stranger Things",
    "charms": 6
  }
];

/** Charm artwork present on the website. Lower than CHARM_TOTAL: the site
 *  does not ship art for every charm the app has. */
export const WEBSITE_ARTWORK = 75;

/** Charms the website names in a collection. Not the shipped total. */
export const CHARM_IN_COLLECTIONS = 55;

/** Categories in the shipped catalogue. */
export const COLLECTION_COUNT = 14;

/** Seasonal and lucky charms that belong to no collection. */
export const SEASONAL = [
  "bat",
  "bell",
  "candyCane",
  "daruma",
  "diya",
  "firework",
  "ghanta",
  "ghost",
  "himmeli",
  "horseshoe",
  "lantern",
  "lotus",
  "luckyCoin",
  "manekiNeko",
  "nimbuMirchi",
  "panchangJie",
  "pumpkin",
  "scarab",
  "shazamLightning",
  "snowflake"
];

export const SEASONAL_COUNT = 11;

/** Deprecated alias. Prefer CHARM_IN_COLLECTIONS, or CHARM_TOTAL to quote. */
export const CHARM_COUNT = 55;

export const ARTWORK = {"plain":75,"connected":75,"complete":75};

export const RELEASE = {
  "macOS": {
    "version": "2.0.0",
    "minimumSystem": "14.0",
    "bytes": 34238650,
    "date": "2026-09-18"
  },
  "windows": "0.9.4"
};

export const GENERATED_AT = "2026-09-25";
