// Generated by scripts/generate-stats.mjs. Do not edit — change the source data.
export type CharmCollection = { name: string; description: string; charms: string[] };

/** Collections and their charms, read from the component that renders them. */
export const COLLECTIONS: CharmCollection[] = [
  {
    "name": "Protection",
    "description": "",
    "charms": [
      "Nazar boncuğu",
      "Hamsa",
      "Nimbu-mirchi",
      "Drishti bommai",
      "Scarab",
      "Dream Catcher"
    ]
  },
  {
    "name": "Luck & Fortune",
    "description": "",
    "charms": [
      "Pánchángjié",
      "Daruma",
      "Maneki-neko",
      "Horseshoe"
    ]
  },
  {
    "name": "Ritual & Home",
    "description": "",
    "charms": [
      "Ghanta",
      "Himmeli"
    ]
  },
  {
    "name": "Classic",
    "description": "",
    "charms": [
      "Bead",
      "Star",
      "Heart",
      "Diamond",
      "Camera"
    ]
  },
  {
    "name": "Marvel",
    "description": "",
    "charms": [
      "Spider-Man",
      "Spider-Man Swinging",
      "Captain America Shield",
      "Iron Man Helmet",
      "Thor Hammer",
      "Hulk Fist",
      "Spider-Man and Gwen",
      "Eye of Agamotto",
      "Stormbreaker",
      "Doctor Doom",
      "Deadpool and Wolverine"
    ]
  },
  {
    "name": "DC",
    "description": "",
    "charms": [
      "Batman Symbol",
      "Superman Shield",
      "Wonder Woman Emblem",
      "Shazam Lightning",
      "Green Lantern Ring"
    ]
  },
  {
    "name": "Spirituality",
    "description": "",
    "charms": [
      "Vel",
      "Vinayagar Coin",
      "OM Symbol",
      "Karuppu Statue",
      "Temple Bell",
      "Rudraksha",
      "Shiva Lingam",
      "Buddha",
      "Hanuman",
      "Kaaba",
      "Green Dome",
      "Crescent and Star",
      "Allah Pendant",
      "Cross",
      "Dove of Peace",
      "Praying Angel",
      "Sacred Heart"
    ]
  },
  {
    "name": "BTS",
    "description": "",
    "charms": [
      "RM",
      "Jin",
      "SUGA",
      "j-hope",
      "Jimin",
      "V",
      "Jungkook"
    ]
  },
  {
    "name": "Football Legends",
    "description": "",
    "charms": [
      "Ronaldo 7",
      "Messi 10",
      "Neymar 10",
      "Real Madrid",
      "FC Barcelona",
      "Ronaldo Portugal",
      "Ronaldo Bicycle Kick",
      "Ballon d'Or",
      "Champions League Trophy",
      "Messi"
    ]
  },
  {
    "name": "Music Legends",
    "description": "",
    "charms": [
      "Billie Eilish",
      "XXXTentacion",
      "Michael Jackson",
      "Taylor Swift",
      "Juice WRLD",
      "The Weeknd"
    ]
  },
  {
    "name": "Friends",
    "description": "",
    "charms": [
      "Rachel Green",
      "Monica Geller",
      "Ross Geller",
      "Joey Tribbiani",
      "Chandler Bing",
      "Phoebe Buffay"
    ]
  },
  {
    "name": "Breaking Bad",
    "description": "",
    "charms": [
      "Walter White",
      "Jesse Pinkman",
      "Saul Goodman",
      "Gus Fring",
      "Mike Ehrmantraut",
      "Heisenberg",
      "RV"
    ]
  },
  {
    "name": "Stranger Things",
    "description": "",
    "charms": [
      "Eleven",
      "Mike Wheeler",
      "Dustin Henderson",
      "Lucas Sinclair",
      "Will Byers",
      "Demogorgon",
      "Max Mayfield",
      "Steve Harrington"
    ]
  },
  {
    "name": "One Piece",
    "description": "",
    "charms": [
      "Monkey D. Luffy",
      "Roronoa Zoro",
      "Nami",
      "Usopp",
      "Sanji",
      "Tony Tony Chopper",
      "Nico Robin",
      "Portgas D. Ace"
    ]
  },
  {
    "name": "Harry Potter",
    "description": "",
    "charms": [
      "Harry Potter",
      "Hermione Granger",
      "Ron Weasley",
      "Albus Dumbledore",
      "Lord Voldemort",
      "Hedwig",
      "Golden Snitch",
      "Deathly Hallows"
    ]
  },
  {
    "name": "Ben 10",
    "description": "",
    "charms": [
      "Ben Tennyson",
      "Four Arms",
      "Heatblast",
      "XLR8",
      "Diamondhead",
      "Cannonbolt",
      "Upgrade",
      "Wildmutt",
      "Omnitrix"
    ]
  },
  {
    "name": "Attack on Titan",
    "description": "",
    "charms": [
      "Eren Yeager",
      "Mikasa Ackerman",
      "Levi Ackerman",
      "Armin Arlert",
      "Colossal Titan",
      "Attack Titan",
      "Survey Corps Emblem",
      "Cadet Corps Emblem"
    ]
  },
  {
    "name": "Naruto",
    "description": "",
    "charms": [
      "Naruto Uzumaki",
      "Sasuke Uchiha",
      "Kakashi Hatake",
      "Itachi Uchiha",
      "Minato Namikaze",
      "Kurama",
      "Akatsuki Cloud",
      "Mangekyō Sharingan"
    ]
  },
  {
    "name": "Game of Thrones",
    "description": "",
    "charms": [
      "Jon Snow",
      "Daenerys Targaryen",
      "Tyrion Lannister",
      "Night King",
      "House Stark",
      "House Targaryen",
      "House Lannister",
      "Iron Throne"
    ]
  },
  {
    "name": "Air Jordan",
    "description": "",
    "charms": [
      "Air Jordan 1 Chicago",
      "Air Jordan 1 Bred Patent",
      "Air Jordan 4 Fire Red",
      "Air Jordan 11 Concord",
      "Air Jordan 3",
      "Air Jordan 6 Carmine",
      "Air Jordan 5",
      "Off-White Air Jordan 1"
    ]
  },
  {
    "name": "Pokémon",
    "description": "",
    "charms": [
      "Pikachu",
      "Charmander",
      "Squirtle",
      "Bulbasaur",
      "Charizard",
      "Dragonair",
      "Mewtwo",
      "Umbreon",
      "Ash and Pikachu",
      "Poké Ball"
    ]
  }
];

/**
 * The number to quote. Every charm whose artwork ships complete — both the
 * plain drawing and the connected one with the thread attached.
 *
 * This is the honest public figure. It is not the collection total: twenty
 * seasonal and lucky charms ship without belonging to a named collection.
 */
export const CHARM_TOTAL = 161;

/** Categories in the shipped catalogue, with their sizes. */
export const SHIPPED_CATEGORIES = [
  {
    "id": "protection",
    "name": "Protection",
    "charms": 6
  },
  {
    "id": "luck",
    "name": "Luck & Fortune",
    "charms": 4
  },
  {
    "id": "ritual",
    "name": "Ritual & Home",
    "charms": 2
  },
  {
    "id": "classic",
    "name": "Classic",
    "charms": 5
  },
  {
    "id": "marvel",
    "name": "Marvel",
    "charms": 11
  },
  {
    "id": "dc",
    "name": "DC",
    "charms": 5
  },
  {
    "id": "tamilSpiritual",
    "name": "Spirituality",
    "charms": 17
  },
  {
    "id": "bts",
    "name": "BTS",
    "charms": 7
  },
  {
    "id": "footballLegends",
    "name": "Football Legends",
    "charms": 10
  },
  {
    "id": "musicLegends",
    "name": "Music Legends",
    "charms": 6
  },
  {
    "id": "friends",
    "name": "Friends",
    "charms": 6
  },
  {
    "id": "breakingBad",
    "name": "Breaking Bad",
    "charms": 7
  },
  {
    "id": "strangerThings",
    "name": "Stranger Things",
    "charms": 8
  },
  {
    "id": "onePiece",
    "name": "One Piece",
    "charms": 8
  },
  {
    "id": "harryPotter",
    "name": "Harry Potter",
    "charms": 8
  },
  {
    "id": "ben10",
    "name": "Ben 10",
    "charms": 9
  },
  {
    "id": "attackOnTitan",
    "name": "Attack on Titan",
    "charms": 8
  },
  {
    "id": "naruto",
    "name": "Naruto",
    "charms": 8
  },
  {
    "id": "gameOfThrones",
    "name": "Game of Thrones",
    "charms": 8
  },
  {
    "id": "airJordan",
    "name": "Air Jordan",
    "charms": 8
  },
  {
    "id": "pokemon",
    "name": "Pokémon",
    "charms": 10
  }
];

/** Charm artwork present on the website. Lower than CHARM_TOTAL: the site
 *  does not ship art for every charm the app has. */
export const WEBSITE_ARTWORK = 75;

/** Charms the website names in a collection. Not the shipped total. */
export const CHARM_IN_COLLECTIONS = 161;

/** Categories in the shipped catalogue. */
export const COLLECTION_COUNT = 21;

/** Seasonal and lucky charms that belong to no collection. */
export const SEASONAL = [];

export const SEASONAL_COUNT = 0;

/** Deprecated alias. Prefer CHARM_IN_COLLECTIONS, or CHARM_TOTAL to quote. */
export const CHARM_COUNT = 161;

export const ARTWORK = {"plain":75,"connected":75,"complete":75};

export const RELEASE = {
  "macOS": {
    "version": "2.3.1",
    "minimumSystem": "14.0",
    "bytes": 84088723,
    "date": "2026-10-06"
  },
  "windows": "2.3.1"
};

export const GENERATED_AT = "2026-10-09";
