// Generated by scripts/generate-stats.mjs. Do not edit — change the source data.
export type CharmCollection = { name: string; description: string; charms: string[] };

/** Collections and their charms, read from the component that renders them. */
export const COLLECTIONS: CharmCollection[] = [
  {
    "name": "Protection",
    "description": "A little luck. A little protection. A feeling of home.",
    "charms": [
      "Nazar / Evil Eye",
      "Drishti Bommai",
      "Hamsa"
    ]
  },
  {
    "name": "Marvel",
    "description": "For the hero behind the screen.",
    "charms": [
      "Spider-Man",
      "Captain America Shield",
      "Iron Man Helmet",
      "Thor Hammer",
      "Hulk Fist"
    ]
  },
  {
    "name": "DC",
    "description": "Iconic symbols. Extraordinary company.",
    "charms": [
      "Batman",
      "Superman",
      "Wonder Woman",
      "Flash",
      "Green Lantern"
    ]
  },
  {
    "name": "Tamil Divine",
    "description": "Sacred symbols. Familiar stories. Close to home.",
    "charms": [
      "Vel",
      "Vinayagar",
      "Om",
      "Karuppu",
      "Temple Bell"
    ]
  },
  {
    "name": "BTS",
    "description": "A little purple in your everyday.",
    "charms": [
      "Jin",
      "Suga",
      "J-Hope",
      "RM",
      "Jimin",
      "V",
      "Jung Kook"
    ]
  },
  {
    "name": "Football",
    "description": "A little piece of match day, always within reach.",
    "charms": [
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Neymar Jr.",
      "Real Madrid",
      "FC Barcelona"
    ]
  },
  {
    "name": "Stranger Things",
    "description": "For late-night mysteries and the bravest of friends.",
    "charms": [
      "Eleven",
      "Mike Wheeler",
      "Dustin Henderson",
      "Lucas Sinclair",
      "Will Byers",
      "Demogorgon"
    ]
  },
  {
    "name": "Singers",
    "description": "A little music for every moment on your desktop.",
    "charms": [
      "Billie Eilish",
      "XXXTENTACION",
      "Michael Jackson",
      "Taylor Swift",
      "Juice WRLD"
    ]
  },
  {
    "name": "Breaking Bad",
    "description": "A little danger. A lot of story.",
    "charms": [
      "Walter White",
      "Jesse Pinkman",
      "Saul Goodman",
      "Gus Fring",
      "Mike Ehrmantraut",
      "Heisenberg",
      "The RV"
    ]
  },
  {
    "name": "Friends",
    "description": "The one with your favorite everyday keepsakes.",
    "charms": [
      "Rachel Green",
      "Monica Geller",
      "Ross Geller",
      "Joey Tribbiani",
      "Chandler Bing",
      "Phoebe Buffay"
    ]
  },
  {
    "name": "Dream Catcher",
    "description": "A quiet little talisman for your day.",
    "charms": [
      "Dream Catcher"
    ]
  }
];

/** Charms listed across every collection on the product page. */
export const CHARM_COUNT = 55;

/** SVG files present in public/charms. Higher than CHARM_COUNT: it includes
 *  artwork for charms not currently listed in a collection. */
export const ARTWORK = {"plain":75,"connected":75};

export const RELEASE = {
  "macOS": {
    "version": "2.0.0",
    "minimumSystem": "14.0",
    "bytes": 34238650,
    "date": "2026-09-18"
  },
  "windows": "0.9.4"
};

export const GENERATED_AT = "2026-09-25";
